
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TipoEvento = {
  GRATIS: 'GRATIS',
  PAGO: 'PAGO'
} as const

export type TipoEvento = (typeof TipoEvento)[keyof typeof TipoEvento]


export const Estado = {
  PENDIENTE: 'PENDIENTE',
  APROBADO: 'APROBADO',
  RECHAZADO: 'RECHAZADO'
} as const

export type Estado = (typeof Estado)[keyof typeof Estado]
