
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Iglesia.ts'
export type * from './models/Rol.ts'
export type * from './models/Usuario.ts'
export type * from './models/Evento.ts'
export type * from './models/Inscripcion.ts'
export type * from './models/Solicitud.ts'
export type * from './commonInputTypes.ts'