
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Iglesia` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Iglesia
 * 
 */
export type IglesiaModel = runtime.Types.Result.DefaultSelection<Prisma.$IglesiaPayload>

export type AggregateIglesia = {
  _count: IglesiaCountAggregateOutputType | null
  _min: IglesiaMinAggregateOutputType | null
  _max: IglesiaMaxAggregateOutputType | null
}

export type IglesiaMinAggregateOutputType = {
  id: string | null
  nombre: string | null
  direccion: string | null
  historia: string | null
  created_at: Date | null
}

export type IglesiaMaxAggregateOutputType = {
  id: string | null
  nombre: string | null
  direccion: string | null
  historia: string | null
  created_at: Date | null
}

export type IglesiaCountAggregateOutputType = {
  id: number
  nombre: number
  direccion: number
  historia: number
  created_at: number
  _all: number
}


export type IglesiaMinAggregateInputType = {
  id?: true
  nombre?: true
  direccion?: true
  historia?: true
  created_at?: true
}

export type IglesiaMaxAggregateInputType = {
  id?: true
  nombre?: true
  direccion?: true
  historia?: true
  created_at?: true
}

export type IglesiaCountAggregateInputType = {
  id?: true
  nombre?: true
  direccion?: true
  historia?: true
  created_at?: true
  _all?: true
}

export type IglesiaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Iglesia to aggregate.
   */
  where?: Prisma.IglesiaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Iglesias to fetch.
   */
  orderBy?: Prisma.IglesiaOrderByWithRelationInput | Prisma.IglesiaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IglesiaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Iglesias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Iglesias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Iglesias
  **/
  _count?: true | IglesiaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IglesiaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IglesiaMaxAggregateInputType
}

export type GetIglesiaAggregateType<T extends IglesiaAggregateArgs> = {
      [P in keyof T & keyof AggregateIglesia]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIglesia[P]>
    : Prisma.GetScalarType<T[P], AggregateIglesia[P]>
}




export type IglesiaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IglesiaWhereInput
  orderBy?: Prisma.IglesiaOrderByWithAggregationInput | Prisma.IglesiaOrderByWithAggregationInput[]
  by: Prisma.IglesiaScalarFieldEnum[] | Prisma.IglesiaScalarFieldEnum
  having?: Prisma.IglesiaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IglesiaCountAggregateInputType | true
  _min?: IglesiaMinAggregateInputType
  _max?: IglesiaMaxAggregateInputType
}

export type IglesiaGroupByOutputType = {
  id: string
  nombre: string
  direccion: string
  historia: string
  created_at: Date
  _count: IglesiaCountAggregateOutputType | null
  _min: IglesiaMinAggregateOutputType | null
  _max: IglesiaMaxAggregateOutputType | null
}

export type GetIglesiaGroupByPayload<T extends IglesiaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IglesiaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IglesiaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IglesiaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IglesiaGroupByOutputType[P]>
      }
    >
  >



export type IglesiaWhereInput = {
  AND?: Prisma.IglesiaWhereInput | Prisma.IglesiaWhereInput[]
  OR?: Prisma.IglesiaWhereInput[]
  NOT?: Prisma.IglesiaWhereInput | Prisma.IglesiaWhereInput[]
  id?: Prisma.StringFilter<"Iglesia"> | string
  nombre?: Prisma.StringFilter<"Iglesia"> | string
  direccion?: Prisma.StringFilter<"Iglesia"> | string
  historia?: Prisma.StringFilter<"Iglesia"> | string
  created_at?: Prisma.DateTimeFilter<"Iglesia"> | Date | string
  usuarios?: Prisma.UsuarioListRelationFilter
  eventos?: Prisma.EventoListRelationFilter
}

export type IglesiaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  direccion?: Prisma.SortOrder
  historia?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  usuarios?: Prisma.UsuarioOrderByRelationAggregateInput
  eventos?: Prisma.EventoOrderByRelationAggregateInput
}

export type IglesiaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.IglesiaWhereInput | Prisma.IglesiaWhereInput[]
  OR?: Prisma.IglesiaWhereInput[]
  NOT?: Prisma.IglesiaWhereInput | Prisma.IglesiaWhereInput[]
  nombre?: Prisma.StringFilter<"Iglesia"> | string
  direccion?: Prisma.StringFilter<"Iglesia"> | string
  historia?: Prisma.StringFilter<"Iglesia"> | string
  created_at?: Prisma.DateTimeFilter<"Iglesia"> | Date | string
  usuarios?: Prisma.UsuarioListRelationFilter
  eventos?: Prisma.EventoListRelationFilter
}, "id">

export type IglesiaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  direccion?: Prisma.SortOrder
  historia?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.IglesiaCountOrderByAggregateInput
  _max?: Prisma.IglesiaMaxOrderByAggregateInput
  _min?: Prisma.IglesiaMinOrderByAggregateInput
}

export type IglesiaScalarWhereWithAggregatesInput = {
  AND?: Prisma.IglesiaScalarWhereWithAggregatesInput | Prisma.IglesiaScalarWhereWithAggregatesInput[]
  OR?: Prisma.IglesiaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IglesiaScalarWhereWithAggregatesInput | Prisma.IglesiaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Iglesia"> | string
  nombre?: Prisma.StringWithAggregatesFilter<"Iglesia"> | string
  direccion?: Prisma.StringWithAggregatesFilter<"Iglesia"> | string
  historia?: Prisma.StringWithAggregatesFilter<"Iglesia"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Iglesia"> | Date | string
}

export type IglesiaCreateInput = {
  id?: string
  nombre: string
  direccion: string
  historia: string
  created_at?: Date | string
  usuarios?: Prisma.UsuarioCreateNestedManyWithoutIglesiaInput
  eventos?: Prisma.EventoCreateNestedManyWithoutIglesiaInput
}

export type IglesiaUncheckedCreateInput = {
  id?: string
  nombre: string
  direccion: string
  historia: string
  created_at?: Date | string
  usuarios?: Prisma.UsuarioUncheckedCreateNestedManyWithoutIglesiaInput
  eventos?: Prisma.EventoUncheckedCreateNestedManyWithoutIglesiaInput
}

export type IglesiaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  historia?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarios?: Prisma.UsuarioUpdateManyWithoutIglesiaNestedInput
  eventos?: Prisma.EventoUpdateManyWithoutIglesiaNestedInput
}

export type IglesiaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  historia?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarios?: Prisma.UsuarioUncheckedUpdateManyWithoutIglesiaNestedInput
  eventos?: Prisma.EventoUncheckedUpdateManyWithoutIglesiaNestedInput
}

export type IglesiaCreateManyInput = {
  id?: string
  nombre: string
  direccion: string
  historia: string
  created_at?: Date | string
}

export type IglesiaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  historia?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IglesiaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  historia?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IglesiaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  direccion?: Prisma.SortOrder
  historia?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type IglesiaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  direccion?: Prisma.SortOrder
  historia?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type IglesiaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  direccion?: Prisma.SortOrder
  historia?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type IglesiaScalarRelationFilter = {
  is?: Prisma.IglesiaWhereInput
  isNot?: Prisma.IglesiaWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IglesiaCreateNestedOneWithoutUsuariosInput = {
  create?: Prisma.XOR<Prisma.IglesiaCreateWithoutUsuariosInput, Prisma.IglesiaUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.IglesiaCreateOrConnectWithoutUsuariosInput
  connect?: Prisma.IglesiaWhereUniqueInput
}

export type IglesiaUpdateOneRequiredWithoutUsuariosNestedInput = {
  create?: Prisma.XOR<Prisma.IglesiaCreateWithoutUsuariosInput, Prisma.IglesiaUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.IglesiaCreateOrConnectWithoutUsuariosInput
  upsert?: Prisma.IglesiaUpsertWithoutUsuariosInput
  connect?: Prisma.IglesiaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.IglesiaUpdateToOneWithWhereWithoutUsuariosInput, Prisma.IglesiaUpdateWithoutUsuariosInput>, Prisma.IglesiaUncheckedUpdateWithoutUsuariosInput>
}

export type IglesiaCreateNestedOneWithoutEventosInput = {
  create?: Prisma.XOR<Prisma.IglesiaCreateWithoutEventosInput, Prisma.IglesiaUncheckedCreateWithoutEventosInput>
  connectOrCreate?: Prisma.IglesiaCreateOrConnectWithoutEventosInput
  connect?: Prisma.IglesiaWhereUniqueInput
}

export type IglesiaUpdateOneRequiredWithoutEventosNestedInput = {
  create?: Prisma.XOR<Prisma.IglesiaCreateWithoutEventosInput, Prisma.IglesiaUncheckedCreateWithoutEventosInput>
  connectOrCreate?: Prisma.IglesiaCreateOrConnectWithoutEventosInput
  upsert?: Prisma.IglesiaUpsertWithoutEventosInput
  connect?: Prisma.IglesiaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.IglesiaUpdateToOneWithWhereWithoutEventosInput, Prisma.IglesiaUpdateWithoutEventosInput>, Prisma.IglesiaUncheckedUpdateWithoutEventosInput>
}

export type IglesiaCreateWithoutUsuariosInput = {
  id?: string
  nombre: string
  direccion: string
  historia: string
  created_at?: Date | string
  eventos?: Prisma.EventoCreateNestedManyWithoutIglesiaInput
}

export type IglesiaUncheckedCreateWithoutUsuariosInput = {
  id?: string
  nombre: string
  direccion: string
  historia: string
  created_at?: Date | string
  eventos?: Prisma.EventoUncheckedCreateNestedManyWithoutIglesiaInput
}

export type IglesiaCreateOrConnectWithoutUsuariosInput = {
  where: Prisma.IglesiaWhereUniqueInput
  create: Prisma.XOR<Prisma.IglesiaCreateWithoutUsuariosInput, Prisma.IglesiaUncheckedCreateWithoutUsuariosInput>
}

export type IglesiaUpsertWithoutUsuariosInput = {
  update: Prisma.XOR<Prisma.IglesiaUpdateWithoutUsuariosInput, Prisma.IglesiaUncheckedUpdateWithoutUsuariosInput>
  create: Prisma.XOR<Prisma.IglesiaCreateWithoutUsuariosInput, Prisma.IglesiaUncheckedCreateWithoutUsuariosInput>
  where?: Prisma.IglesiaWhereInput
}

export type IglesiaUpdateToOneWithWhereWithoutUsuariosInput = {
  where?: Prisma.IglesiaWhereInput
  data: Prisma.XOR<Prisma.IglesiaUpdateWithoutUsuariosInput, Prisma.IglesiaUncheckedUpdateWithoutUsuariosInput>
}

export type IglesiaUpdateWithoutUsuariosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  historia?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventos?: Prisma.EventoUpdateManyWithoutIglesiaNestedInput
}

export type IglesiaUncheckedUpdateWithoutUsuariosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  historia?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventos?: Prisma.EventoUncheckedUpdateManyWithoutIglesiaNestedInput
}

export type IglesiaCreateWithoutEventosInput = {
  id?: string
  nombre: string
  direccion: string
  historia: string
  created_at?: Date | string
  usuarios?: Prisma.UsuarioCreateNestedManyWithoutIglesiaInput
}

export type IglesiaUncheckedCreateWithoutEventosInput = {
  id?: string
  nombre: string
  direccion: string
  historia: string
  created_at?: Date | string
  usuarios?: Prisma.UsuarioUncheckedCreateNestedManyWithoutIglesiaInput
}

export type IglesiaCreateOrConnectWithoutEventosInput = {
  where: Prisma.IglesiaWhereUniqueInput
  create: Prisma.XOR<Prisma.IglesiaCreateWithoutEventosInput, Prisma.IglesiaUncheckedCreateWithoutEventosInput>
}

export type IglesiaUpsertWithoutEventosInput = {
  update: Prisma.XOR<Prisma.IglesiaUpdateWithoutEventosInput, Prisma.IglesiaUncheckedUpdateWithoutEventosInput>
  create: Prisma.XOR<Prisma.IglesiaCreateWithoutEventosInput, Prisma.IglesiaUncheckedCreateWithoutEventosInput>
  where?: Prisma.IglesiaWhereInput
}

export type IglesiaUpdateToOneWithWhereWithoutEventosInput = {
  where?: Prisma.IglesiaWhereInput
  data: Prisma.XOR<Prisma.IglesiaUpdateWithoutEventosInput, Prisma.IglesiaUncheckedUpdateWithoutEventosInput>
}

export type IglesiaUpdateWithoutEventosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  historia?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarios?: Prisma.UsuarioUpdateManyWithoutIglesiaNestedInput
}

export type IglesiaUncheckedUpdateWithoutEventosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  historia?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarios?: Prisma.UsuarioUncheckedUpdateManyWithoutIglesiaNestedInput
}


/**
 * Count Type IglesiaCountOutputType
 */

export type IglesiaCountOutputType = {
  usuarios: number
  eventos: number
}

export type IglesiaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuarios?: boolean | IglesiaCountOutputTypeCountUsuariosArgs
  eventos?: boolean | IglesiaCountOutputTypeCountEventosArgs
}

/**
 * IglesiaCountOutputType without action
 */
export type IglesiaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IglesiaCountOutputType
   */
  select?: Prisma.IglesiaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * IglesiaCountOutputType without action
 */
export type IglesiaCountOutputTypeCountUsuariosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UsuarioWhereInput
}

/**
 * IglesiaCountOutputType without action
 */
export type IglesiaCountOutputTypeCountEventosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventoWhereInput
}


export type IglesiaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  direccion?: boolean
  historia?: boolean
  created_at?: boolean
  usuarios?: boolean | Prisma.Iglesia$usuariosArgs<ExtArgs>
  eventos?: boolean | Prisma.Iglesia$eventosArgs<ExtArgs>
  _count?: boolean | Prisma.IglesiaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["iglesia"]>

export type IglesiaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  direccion?: boolean
  historia?: boolean
  created_at?: boolean
}, ExtArgs["result"]["iglesia"]>

export type IglesiaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  direccion?: boolean
  historia?: boolean
  created_at?: boolean
}, ExtArgs["result"]["iglesia"]>

export type IglesiaSelectScalar = {
  id?: boolean
  nombre?: boolean
  direccion?: boolean
  historia?: boolean
  created_at?: boolean
}

export type IglesiaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nombre" | "direccion" | "historia" | "created_at", ExtArgs["result"]["iglesia"]>
export type IglesiaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuarios?: boolean | Prisma.Iglesia$usuariosArgs<ExtArgs>
  eventos?: boolean | Prisma.Iglesia$eventosArgs<ExtArgs>
  _count?: boolean | Prisma.IglesiaCountOutputTypeDefaultArgs<ExtArgs>
}
export type IglesiaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type IglesiaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $IglesiaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Iglesia"
  objects: {
    usuarios: Prisma.$UsuarioPayload<ExtArgs>[]
    eventos: Prisma.$EventoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nombre: string
    direccion: string
    historia: string
    created_at: Date
  }, ExtArgs["result"]["iglesia"]>
  composites: {}
}

export type IglesiaGetPayload<S extends boolean | null | undefined | IglesiaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IglesiaPayload, S>

export type IglesiaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IglesiaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IglesiaCountAggregateInputType | true
  }

export interface IglesiaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Iglesia'], meta: { name: 'Iglesia' } }
  /**
   * Find zero or one Iglesia that matches the filter.
   * @param {IglesiaFindUniqueArgs} args - Arguments to find a Iglesia
   * @example
   * // Get one Iglesia
   * const iglesia = await prisma.iglesia.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IglesiaFindUniqueArgs>(args: Prisma.SelectSubset<T, IglesiaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IglesiaClient<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Iglesia that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IglesiaFindUniqueOrThrowArgs} args - Arguments to find a Iglesia
   * @example
   * // Get one Iglesia
   * const iglesia = await prisma.iglesia.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IglesiaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IglesiaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IglesiaClient<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Iglesia that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IglesiaFindFirstArgs} args - Arguments to find a Iglesia
   * @example
   * // Get one Iglesia
   * const iglesia = await prisma.iglesia.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IglesiaFindFirstArgs>(args?: Prisma.SelectSubset<T, IglesiaFindFirstArgs<ExtArgs>>): Prisma.Prisma__IglesiaClient<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Iglesia that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IglesiaFindFirstOrThrowArgs} args - Arguments to find a Iglesia
   * @example
   * // Get one Iglesia
   * const iglesia = await prisma.iglesia.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IglesiaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IglesiaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IglesiaClient<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Iglesias that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IglesiaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Iglesias
   * const iglesias = await prisma.iglesia.findMany()
   * 
   * // Get first 10 Iglesias
   * const iglesias = await prisma.iglesia.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const iglesiaWithIdOnly = await prisma.iglesia.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends IglesiaFindManyArgs>(args?: Prisma.SelectSubset<T, IglesiaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Iglesia.
   * @param {IglesiaCreateArgs} args - Arguments to create a Iglesia.
   * @example
   * // Create one Iglesia
   * const Iglesia = await prisma.iglesia.create({
   *   data: {
   *     // ... data to create a Iglesia
   *   }
   * })
   * 
   */
  create<T extends IglesiaCreateArgs>(args: Prisma.SelectSubset<T, IglesiaCreateArgs<ExtArgs>>): Prisma.Prisma__IglesiaClient<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Iglesias.
   * @param {IglesiaCreateManyArgs} args - Arguments to create many Iglesias.
   * @example
   * // Create many Iglesias
   * const iglesia = await prisma.iglesia.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IglesiaCreateManyArgs>(args?: Prisma.SelectSubset<T, IglesiaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Iglesias and returns the data saved in the database.
   * @param {IglesiaCreateManyAndReturnArgs} args - Arguments to create many Iglesias.
   * @example
   * // Create many Iglesias
   * const iglesia = await prisma.iglesia.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Iglesias and only return the `id`
   * const iglesiaWithIdOnly = await prisma.iglesia.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends IglesiaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, IglesiaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Iglesia.
   * @param {IglesiaDeleteArgs} args - Arguments to delete one Iglesia.
   * @example
   * // Delete one Iglesia
   * const Iglesia = await prisma.iglesia.delete({
   *   where: {
   *     // ... filter to delete one Iglesia
   *   }
   * })
   * 
   */
  delete<T extends IglesiaDeleteArgs>(args: Prisma.SelectSubset<T, IglesiaDeleteArgs<ExtArgs>>): Prisma.Prisma__IglesiaClient<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Iglesia.
   * @param {IglesiaUpdateArgs} args - Arguments to update one Iglesia.
   * @example
   * // Update one Iglesia
   * const iglesia = await prisma.iglesia.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IglesiaUpdateArgs>(args: Prisma.SelectSubset<T, IglesiaUpdateArgs<ExtArgs>>): Prisma.Prisma__IglesiaClient<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Iglesias.
   * @param {IglesiaDeleteManyArgs} args - Arguments to filter Iglesias to delete.
   * @example
   * // Delete a few Iglesias
   * const { count } = await prisma.iglesia.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IglesiaDeleteManyArgs>(args?: Prisma.SelectSubset<T, IglesiaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Iglesias.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IglesiaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Iglesias
   * const iglesia = await prisma.iglesia.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IglesiaUpdateManyArgs>(args: Prisma.SelectSubset<T, IglesiaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Iglesias and returns the data updated in the database.
   * @param {IglesiaUpdateManyAndReturnArgs} args - Arguments to update many Iglesias.
   * @example
   * // Update many Iglesias
   * const iglesia = await prisma.iglesia.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Iglesias and only return the `id`
   * const iglesiaWithIdOnly = await prisma.iglesia.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends IglesiaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, IglesiaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Iglesia.
   * @param {IglesiaUpsertArgs} args - Arguments to update or create a Iglesia.
   * @example
   * // Update or create a Iglesia
   * const iglesia = await prisma.iglesia.upsert({
   *   create: {
   *     // ... data to create a Iglesia
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Iglesia we want to update
   *   }
   * })
   */
  upsert<T extends IglesiaUpsertArgs>(args: Prisma.SelectSubset<T, IglesiaUpsertArgs<ExtArgs>>): Prisma.Prisma__IglesiaClient<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Iglesias.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IglesiaCountArgs} args - Arguments to filter Iglesias to count.
   * @example
   * // Count the number of Iglesias
   * const count = await prisma.iglesia.count({
   *   where: {
   *     // ... the filter for the Iglesias we want to count
   *   }
   * })
  **/
  count<T extends IglesiaCountArgs>(
    args?: Prisma.Subset<T, IglesiaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IglesiaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Iglesia.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IglesiaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IglesiaAggregateArgs>(args: Prisma.Subset<T, IglesiaAggregateArgs>): Prisma.PrismaPromise<GetIglesiaAggregateType<T>>

  /**
   * Group by Iglesia.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IglesiaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IglesiaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IglesiaGroupByArgs['orderBy'] }
      : { orderBy?: IglesiaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IglesiaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIglesiaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Iglesia model
 */
readonly fields: IglesiaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Iglesia.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IglesiaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  usuarios<T extends Prisma.Iglesia$usuariosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Iglesia$usuariosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  eventos<T extends Prisma.Iglesia$eventosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Iglesia$eventosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Iglesia model
 */
export interface IglesiaFieldRefs {
  readonly id: Prisma.FieldRef<"Iglesia", 'String'>
  readonly nombre: Prisma.FieldRef<"Iglesia", 'String'>
  readonly direccion: Prisma.FieldRef<"Iglesia", 'String'>
  readonly historia: Prisma.FieldRef<"Iglesia", 'String'>
  readonly created_at: Prisma.FieldRef<"Iglesia", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Iglesia findUnique
 */
export type IglesiaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IglesiaInclude<ExtArgs> | null
  /**
   * Filter, which Iglesia to fetch.
   */
  where: Prisma.IglesiaWhereUniqueInput
}

/**
 * Iglesia findUniqueOrThrow
 */
export type IglesiaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IglesiaInclude<ExtArgs> | null
  /**
   * Filter, which Iglesia to fetch.
   */
  where: Prisma.IglesiaWhereUniqueInput
}

/**
 * Iglesia findFirst
 */
export type IglesiaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IglesiaInclude<ExtArgs> | null
  /**
   * Filter, which Iglesia to fetch.
   */
  where?: Prisma.IglesiaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Iglesias to fetch.
   */
  orderBy?: Prisma.IglesiaOrderByWithRelationInput | Prisma.IglesiaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Iglesias.
   */
  cursor?: Prisma.IglesiaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Iglesias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Iglesias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Iglesias.
   */
  distinct?: Prisma.IglesiaScalarFieldEnum | Prisma.IglesiaScalarFieldEnum[]
}

/**
 * Iglesia findFirstOrThrow
 */
export type IglesiaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IglesiaInclude<ExtArgs> | null
  /**
   * Filter, which Iglesia to fetch.
   */
  where?: Prisma.IglesiaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Iglesias to fetch.
   */
  orderBy?: Prisma.IglesiaOrderByWithRelationInput | Prisma.IglesiaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Iglesias.
   */
  cursor?: Prisma.IglesiaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Iglesias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Iglesias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Iglesias.
   */
  distinct?: Prisma.IglesiaScalarFieldEnum | Prisma.IglesiaScalarFieldEnum[]
}

/**
 * Iglesia findMany
 */
export type IglesiaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IglesiaInclude<ExtArgs> | null
  /**
   * Filter, which Iglesias to fetch.
   */
  where?: Prisma.IglesiaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Iglesias to fetch.
   */
  orderBy?: Prisma.IglesiaOrderByWithRelationInput | Prisma.IglesiaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Iglesias.
   */
  cursor?: Prisma.IglesiaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Iglesias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Iglesias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Iglesias.
   */
  distinct?: Prisma.IglesiaScalarFieldEnum | Prisma.IglesiaScalarFieldEnum[]
}

/**
 * Iglesia create
 */
export type IglesiaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IglesiaInclude<ExtArgs> | null
  /**
   * The data needed to create a Iglesia.
   */
  data: Prisma.XOR<Prisma.IglesiaCreateInput, Prisma.IglesiaUncheckedCreateInput>
}

/**
 * Iglesia createMany
 */
export type IglesiaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Iglesias.
   */
  data: Prisma.IglesiaCreateManyInput | Prisma.IglesiaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Iglesia createManyAndReturn
 */
export type IglesiaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * The data used to create many Iglesias.
   */
  data: Prisma.IglesiaCreateManyInput | Prisma.IglesiaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Iglesia update
 */
export type IglesiaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IglesiaInclude<ExtArgs> | null
  /**
   * The data needed to update a Iglesia.
   */
  data: Prisma.XOR<Prisma.IglesiaUpdateInput, Prisma.IglesiaUncheckedUpdateInput>
  /**
   * Choose, which Iglesia to update.
   */
  where: Prisma.IglesiaWhereUniqueInput
}

/**
 * Iglesia updateMany
 */
export type IglesiaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Iglesias.
   */
  data: Prisma.XOR<Prisma.IglesiaUpdateManyMutationInput, Prisma.IglesiaUncheckedUpdateManyInput>
  /**
   * Filter which Iglesias to update
   */
  where?: Prisma.IglesiaWhereInput
  /**
   * Limit how many Iglesias to update.
   */
  limit?: number
}

/**
 * Iglesia updateManyAndReturn
 */
export type IglesiaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * The data used to update Iglesias.
   */
  data: Prisma.XOR<Prisma.IglesiaUpdateManyMutationInput, Prisma.IglesiaUncheckedUpdateManyInput>
  /**
   * Filter which Iglesias to update
   */
  where?: Prisma.IglesiaWhereInput
  /**
   * Limit how many Iglesias to update.
   */
  limit?: number
}

/**
 * Iglesia upsert
 */
export type IglesiaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IglesiaInclude<ExtArgs> | null
  /**
   * The filter to search for the Iglesia to update in case it exists.
   */
  where: Prisma.IglesiaWhereUniqueInput
  /**
   * In case the Iglesia found by the `where` argument doesn't exist, create a new Iglesia with this data.
   */
  create: Prisma.XOR<Prisma.IglesiaCreateInput, Prisma.IglesiaUncheckedCreateInput>
  /**
   * In case the Iglesia was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IglesiaUpdateInput, Prisma.IglesiaUncheckedUpdateInput>
}

/**
 * Iglesia delete
 */
export type IglesiaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IglesiaInclude<ExtArgs> | null
  /**
   * Filter which Iglesia to delete.
   */
  where: Prisma.IglesiaWhereUniqueInput
}

/**
 * Iglesia deleteMany
 */
export type IglesiaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Iglesias to delete
   */
  where?: Prisma.IglesiaWhereInput
  /**
   * Limit how many Iglesias to delete.
   */
  limit?: number
}

/**
 * Iglesia.usuarios
 */
export type Iglesia$usuariosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  where?: Prisma.UsuarioWhereInput
  orderBy?: Prisma.UsuarioOrderByWithRelationInput | Prisma.UsuarioOrderByWithRelationInput[]
  cursor?: Prisma.UsuarioWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UsuarioScalarFieldEnum | Prisma.UsuarioScalarFieldEnum[]
}

/**
 * Iglesia.eventos
 */
export type Iglesia$eventosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evento
   */
  select?: Prisma.EventoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evento
   */
  omit?: Prisma.EventoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventoInclude<ExtArgs> | null
  where?: Prisma.EventoWhereInput
  orderBy?: Prisma.EventoOrderByWithRelationInput | Prisma.EventoOrderByWithRelationInput[]
  cursor?: Prisma.EventoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EventoScalarFieldEnum | Prisma.EventoScalarFieldEnum[]
}

/**
 * Iglesia without action
 */
export type IglesiaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iglesia
   */
  select?: Prisma.IglesiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iglesia
   */
  omit?: Prisma.IglesiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IglesiaInclude<ExtArgs> | null
}
