
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Inscripcion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Inscripcion
 * 
 */
export type InscripcionModel = runtime.Types.Result.DefaultSelection<Prisma.$InscripcionPayload>

export type AggregateInscripcion = {
  _count: InscripcionCountAggregateOutputType | null
  _min: InscripcionMinAggregateOutputType | null
  _max: InscripcionMaxAggregateOutputType | null
}

export type InscripcionMinAggregateOutputType = {
  id: string | null
  usuario_id: string | null
  evento_id: string | null
  estado: $Enums.Estado | null
  comprobante_url: string | null
  created_at: Date | null
}

export type InscripcionMaxAggregateOutputType = {
  id: string | null
  usuario_id: string | null
  evento_id: string | null
  estado: $Enums.Estado | null
  comprobante_url: string | null
  created_at: Date | null
}

export type InscripcionCountAggregateOutputType = {
  id: number
  usuario_id: number
  evento_id: number
  estado: number
  comprobante_url: number
  created_at: number
  _all: number
}


export type InscripcionMinAggregateInputType = {
  id?: true
  usuario_id?: true
  evento_id?: true
  estado?: true
  comprobante_url?: true
  created_at?: true
}

export type InscripcionMaxAggregateInputType = {
  id?: true
  usuario_id?: true
  evento_id?: true
  estado?: true
  comprobante_url?: true
  created_at?: true
}

export type InscripcionCountAggregateInputType = {
  id?: true
  usuario_id?: true
  evento_id?: true
  estado?: true
  comprobante_url?: true
  created_at?: true
  _all?: true
}

export type InscripcionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Inscripcion to aggregate.
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Inscripcions to fetch.
   */
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InscripcionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Inscripcions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Inscripcions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Inscripcions
  **/
  _count?: true | InscripcionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InscripcionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InscripcionMaxAggregateInputType
}

export type GetInscripcionAggregateType<T extends InscripcionAggregateArgs> = {
      [P in keyof T & keyof AggregateInscripcion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInscripcion[P]>
    : Prisma.GetScalarType<T[P], AggregateInscripcion[P]>
}




export type InscripcionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InscripcionWhereInput
  orderBy?: Prisma.InscripcionOrderByWithAggregationInput | Prisma.InscripcionOrderByWithAggregationInput[]
  by: Prisma.InscripcionScalarFieldEnum[] | Prisma.InscripcionScalarFieldEnum
  having?: Prisma.InscripcionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InscripcionCountAggregateInputType | true
  _min?: InscripcionMinAggregateInputType
  _max?: InscripcionMaxAggregateInputType
}

export type InscripcionGroupByOutputType = {
  id: string
  usuario_id: string
  evento_id: string
  estado: $Enums.Estado
  comprobante_url: string | null
  created_at: Date
  _count: InscripcionCountAggregateOutputType | null
  _min: InscripcionMinAggregateOutputType | null
  _max: InscripcionMaxAggregateOutputType | null
}

export type GetInscripcionGroupByPayload<T extends InscripcionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InscripcionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InscripcionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InscripcionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InscripcionGroupByOutputType[P]>
      }
    >
  >



export type InscripcionWhereInput = {
  AND?: Prisma.InscripcionWhereInput | Prisma.InscripcionWhereInput[]
  OR?: Prisma.InscripcionWhereInput[]
  NOT?: Prisma.InscripcionWhereInput | Prisma.InscripcionWhereInput[]
  id?: Prisma.StringFilter<"Inscripcion"> | string
  usuario_id?: Prisma.StringFilter<"Inscripcion"> | string
  evento_id?: Prisma.StringFilter<"Inscripcion"> | string
  estado?: Prisma.EnumEstadoFilter<"Inscripcion"> | $Enums.Estado
  comprobante_url?: Prisma.StringNullableFilter<"Inscripcion"> | string | null
  created_at?: Prisma.DateTimeFilter<"Inscripcion"> | Date | string
  usuario?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  evento?: Prisma.XOR<Prisma.EventoScalarRelationFilter, Prisma.EventoWhereInput>
}

export type InscripcionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  evento_id?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  comprobante_url?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  usuario?: Prisma.UsuarioOrderByWithRelationInput
  evento?: Prisma.EventoOrderByWithRelationInput
}

export type InscripcionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.InscripcionWhereInput | Prisma.InscripcionWhereInput[]
  OR?: Prisma.InscripcionWhereInput[]
  NOT?: Prisma.InscripcionWhereInput | Prisma.InscripcionWhereInput[]
  usuario_id?: Prisma.StringFilter<"Inscripcion"> | string
  evento_id?: Prisma.StringFilter<"Inscripcion"> | string
  estado?: Prisma.EnumEstadoFilter<"Inscripcion"> | $Enums.Estado
  comprobante_url?: Prisma.StringNullableFilter<"Inscripcion"> | string | null
  created_at?: Prisma.DateTimeFilter<"Inscripcion"> | Date | string
  usuario?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  evento?: Prisma.XOR<Prisma.EventoScalarRelationFilter, Prisma.EventoWhereInput>
}, "id">

export type InscripcionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  evento_id?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  comprobante_url?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.InscripcionCountOrderByAggregateInput
  _max?: Prisma.InscripcionMaxOrderByAggregateInput
  _min?: Prisma.InscripcionMinOrderByAggregateInput
}

export type InscripcionScalarWhereWithAggregatesInput = {
  AND?: Prisma.InscripcionScalarWhereWithAggregatesInput | Prisma.InscripcionScalarWhereWithAggregatesInput[]
  OR?: Prisma.InscripcionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InscripcionScalarWhereWithAggregatesInput | Prisma.InscripcionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Inscripcion"> | string
  usuario_id?: Prisma.StringWithAggregatesFilter<"Inscripcion"> | string
  evento_id?: Prisma.StringWithAggregatesFilter<"Inscripcion"> | string
  estado?: Prisma.EnumEstadoWithAggregatesFilter<"Inscripcion"> | $Enums.Estado
  comprobante_url?: Prisma.StringNullableWithAggregatesFilter<"Inscripcion"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Inscripcion"> | Date | string
}

export type InscripcionCreateInput = {
  id?: string
  estado?: $Enums.Estado
  comprobante_url?: string | null
  created_at?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutInscripcionesInput
  evento: Prisma.EventoCreateNestedOneWithoutInscripcionesInput
}

export type InscripcionUncheckedCreateInput = {
  id?: string
  usuario_id: string
  evento_id: string
  estado?: $Enums.Estado
  comprobante_url?: string | null
  created_at?: Date | string
}

export type InscripcionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  comprobante_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutInscripcionesNestedInput
  evento?: Prisma.EventoUpdateOneRequiredWithoutInscripcionesNestedInput
}

export type InscripcionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuario_id?: Prisma.StringFieldUpdateOperationsInput | string
  evento_id?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  comprobante_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionCreateManyInput = {
  id?: string
  usuario_id: string
  evento_id: string
  estado?: $Enums.Estado
  comprobante_url?: string | null
  created_at?: Date | string
}

export type InscripcionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  comprobante_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuario_id?: Prisma.StringFieldUpdateOperationsInput | string
  evento_id?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  comprobante_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionListRelationFilter = {
  every?: Prisma.InscripcionWhereInput
  some?: Prisma.InscripcionWhereInput
  none?: Prisma.InscripcionWhereInput
}

export type InscripcionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InscripcionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  evento_id?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  comprobante_url?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type InscripcionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  evento_id?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  comprobante_url?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type InscripcionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  evento_id?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  comprobante_url?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type InscripcionCreateNestedManyWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutUsuarioInput, Prisma.InscripcionUncheckedCreateWithoutUsuarioInput> | Prisma.InscripcionCreateWithoutUsuarioInput[] | Prisma.InscripcionUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutUsuarioInput | Prisma.InscripcionCreateOrConnectWithoutUsuarioInput[]
  createMany?: Prisma.InscripcionCreateManyUsuarioInputEnvelope
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
}

export type InscripcionUncheckedCreateNestedManyWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutUsuarioInput, Prisma.InscripcionUncheckedCreateWithoutUsuarioInput> | Prisma.InscripcionCreateWithoutUsuarioInput[] | Prisma.InscripcionUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutUsuarioInput | Prisma.InscripcionCreateOrConnectWithoutUsuarioInput[]
  createMany?: Prisma.InscripcionCreateManyUsuarioInputEnvelope
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
}

export type InscripcionUpdateManyWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutUsuarioInput, Prisma.InscripcionUncheckedCreateWithoutUsuarioInput> | Prisma.InscripcionCreateWithoutUsuarioInput[] | Prisma.InscripcionUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutUsuarioInput | Prisma.InscripcionCreateOrConnectWithoutUsuarioInput[]
  upsert?: Prisma.InscripcionUpsertWithWhereUniqueWithoutUsuarioInput | Prisma.InscripcionUpsertWithWhereUniqueWithoutUsuarioInput[]
  createMany?: Prisma.InscripcionCreateManyUsuarioInputEnvelope
  set?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  disconnect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  delete?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  update?: Prisma.InscripcionUpdateWithWhereUniqueWithoutUsuarioInput | Prisma.InscripcionUpdateWithWhereUniqueWithoutUsuarioInput[]
  updateMany?: Prisma.InscripcionUpdateManyWithWhereWithoutUsuarioInput | Prisma.InscripcionUpdateManyWithWhereWithoutUsuarioInput[]
  deleteMany?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
}

export type InscripcionUncheckedUpdateManyWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutUsuarioInput, Prisma.InscripcionUncheckedCreateWithoutUsuarioInput> | Prisma.InscripcionCreateWithoutUsuarioInput[] | Prisma.InscripcionUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutUsuarioInput | Prisma.InscripcionCreateOrConnectWithoutUsuarioInput[]
  upsert?: Prisma.InscripcionUpsertWithWhereUniqueWithoutUsuarioInput | Prisma.InscripcionUpsertWithWhereUniqueWithoutUsuarioInput[]
  createMany?: Prisma.InscripcionCreateManyUsuarioInputEnvelope
  set?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  disconnect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  delete?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  update?: Prisma.InscripcionUpdateWithWhereUniqueWithoutUsuarioInput | Prisma.InscripcionUpdateWithWhereUniqueWithoutUsuarioInput[]
  updateMany?: Prisma.InscripcionUpdateManyWithWhereWithoutUsuarioInput | Prisma.InscripcionUpdateManyWithWhereWithoutUsuarioInput[]
  deleteMany?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
}

export type InscripcionCreateNestedManyWithoutEventoInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutEventoInput, Prisma.InscripcionUncheckedCreateWithoutEventoInput> | Prisma.InscripcionCreateWithoutEventoInput[] | Prisma.InscripcionUncheckedCreateWithoutEventoInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutEventoInput | Prisma.InscripcionCreateOrConnectWithoutEventoInput[]
  createMany?: Prisma.InscripcionCreateManyEventoInputEnvelope
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
}

export type InscripcionUncheckedCreateNestedManyWithoutEventoInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutEventoInput, Prisma.InscripcionUncheckedCreateWithoutEventoInput> | Prisma.InscripcionCreateWithoutEventoInput[] | Prisma.InscripcionUncheckedCreateWithoutEventoInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutEventoInput | Prisma.InscripcionCreateOrConnectWithoutEventoInput[]
  createMany?: Prisma.InscripcionCreateManyEventoInputEnvelope
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
}

export type InscripcionUpdateManyWithoutEventoNestedInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutEventoInput, Prisma.InscripcionUncheckedCreateWithoutEventoInput> | Prisma.InscripcionCreateWithoutEventoInput[] | Prisma.InscripcionUncheckedCreateWithoutEventoInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutEventoInput | Prisma.InscripcionCreateOrConnectWithoutEventoInput[]
  upsert?: Prisma.InscripcionUpsertWithWhereUniqueWithoutEventoInput | Prisma.InscripcionUpsertWithWhereUniqueWithoutEventoInput[]
  createMany?: Prisma.InscripcionCreateManyEventoInputEnvelope
  set?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  disconnect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  delete?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  update?: Prisma.InscripcionUpdateWithWhereUniqueWithoutEventoInput | Prisma.InscripcionUpdateWithWhereUniqueWithoutEventoInput[]
  updateMany?: Prisma.InscripcionUpdateManyWithWhereWithoutEventoInput | Prisma.InscripcionUpdateManyWithWhereWithoutEventoInput[]
  deleteMany?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
}

export type InscripcionUncheckedUpdateManyWithoutEventoNestedInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutEventoInput, Prisma.InscripcionUncheckedCreateWithoutEventoInput> | Prisma.InscripcionCreateWithoutEventoInput[] | Prisma.InscripcionUncheckedCreateWithoutEventoInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutEventoInput | Prisma.InscripcionCreateOrConnectWithoutEventoInput[]
  upsert?: Prisma.InscripcionUpsertWithWhereUniqueWithoutEventoInput | Prisma.InscripcionUpsertWithWhereUniqueWithoutEventoInput[]
  createMany?: Prisma.InscripcionCreateManyEventoInputEnvelope
  set?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  disconnect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  delete?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  update?: Prisma.InscripcionUpdateWithWhereUniqueWithoutEventoInput | Prisma.InscripcionUpdateWithWhereUniqueWithoutEventoInput[]
  updateMany?: Prisma.InscripcionUpdateManyWithWhereWithoutEventoInput | Prisma.InscripcionUpdateManyWithWhereWithoutEventoInput[]
  deleteMany?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
}

export type EnumEstadoFieldUpdateOperationsInput = {
  set?: $Enums.Estado
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type InscripcionCreateWithoutUsuarioInput = {
  id?: string
  estado?: $Enums.Estado
  comprobante_url?: string | null
  created_at?: Date | string
  evento: Prisma.EventoCreateNestedOneWithoutInscripcionesInput
}

export type InscripcionUncheckedCreateWithoutUsuarioInput = {
  id?: string
  evento_id: string
  estado?: $Enums.Estado
  comprobante_url?: string | null
  created_at?: Date | string
}

export type InscripcionCreateOrConnectWithoutUsuarioInput = {
  where: Prisma.InscripcionWhereUniqueInput
  create: Prisma.XOR<Prisma.InscripcionCreateWithoutUsuarioInput, Prisma.InscripcionUncheckedCreateWithoutUsuarioInput>
}

export type InscripcionCreateManyUsuarioInputEnvelope = {
  data: Prisma.InscripcionCreateManyUsuarioInput | Prisma.InscripcionCreateManyUsuarioInput[]
  skipDuplicates?: boolean
}

export type InscripcionUpsertWithWhereUniqueWithoutUsuarioInput = {
  where: Prisma.InscripcionWhereUniqueInput
  update: Prisma.XOR<Prisma.InscripcionUpdateWithoutUsuarioInput, Prisma.InscripcionUncheckedUpdateWithoutUsuarioInput>
  create: Prisma.XOR<Prisma.InscripcionCreateWithoutUsuarioInput, Prisma.InscripcionUncheckedCreateWithoutUsuarioInput>
}

export type InscripcionUpdateWithWhereUniqueWithoutUsuarioInput = {
  where: Prisma.InscripcionWhereUniqueInput
  data: Prisma.XOR<Prisma.InscripcionUpdateWithoutUsuarioInput, Prisma.InscripcionUncheckedUpdateWithoutUsuarioInput>
}

export type InscripcionUpdateManyWithWhereWithoutUsuarioInput = {
  where: Prisma.InscripcionScalarWhereInput
  data: Prisma.XOR<Prisma.InscripcionUpdateManyMutationInput, Prisma.InscripcionUncheckedUpdateManyWithoutUsuarioInput>
}

export type InscripcionScalarWhereInput = {
  AND?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
  OR?: Prisma.InscripcionScalarWhereInput[]
  NOT?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
  id?: Prisma.StringFilter<"Inscripcion"> | string
  usuario_id?: Prisma.StringFilter<"Inscripcion"> | string
  evento_id?: Prisma.StringFilter<"Inscripcion"> | string
  estado?: Prisma.EnumEstadoFilter<"Inscripcion"> | $Enums.Estado
  comprobante_url?: Prisma.StringNullableFilter<"Inscripcion"> | string | null
  created_at?: Prisma.DateTimeFilter<"Inscripcion"> | Date | string
}

export type InscripcionCreateWithoutEventoInput = {
  id?: string
  estado?: $Enums.Estado
  comprobante_url?: string | null
  created_at?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutInscripcionesInput
}

export type InscripcionUncheckedCreateWithoutEventoInput = {
  id?: string
  usuario_id: string
  estado?: $Enums.Estado
  comprobante_url?: string | null
  created_at?: Date | string
}

export type InscripcionCreateOrConnectWithoutEventoInput = {
  where: Prisma.InscripcionWhereUniqueInput
  create: Prisma.XOR<Prisma.InscripcionCreateWithoutEventoInput, Prisma.InscripcionUncheckedCreateWithoutEventoInput>
}

export type InscripcionCreateManyEventoInputEnvelope = {
  data: Prisma.InscripcionCreateManyEventoInput | Prisma.InscripcionCreateManyEventoInput[]
  skipDuplicates?: boolean
}

export type InscripcionUpsertWithWhereUniqueWithoutEventoInput = {
  where: Prisma.InscripcionWhereUniqueInput
  update: Prisma.XOR<Prisma.InscripcionUpdateWithoutEventoInput, Prisma.InscripcionUncheckedUpdateWithoutEventoInput>
  create: Prisma.XOR<Prisma.InscripcionCreateWithoutEventoInput, Prisma.InscripcionUncheckedCreateWithoutEventoInput>
}

export type InscripcionUpdateWithWhereUniqueWithoutEventoInput = {
  where: Prisma.InscripcionWhereUniqueInput
  data: Prisma.XOR<Prisma.InscripcionUpdateWithoutEventoInput, Prisma.InscripcionUncheckedUpdateWithoutEventoInput>
}

export type InscripcionUpdateManyWithWhereWithoutEventoInput = {
  where: Prisma.InscripcionScalarWhereInput
  data: Prisma.XOR<Prisma.InscripcionUpdateManyMutationInput, Prisma.InscripcionUncheckedUpdateManyWithoutEventoInput>
}

export type InscripcionCreateManyUsuarioInput = {
  id?: string
  evento_id: string
  estado?: $Enums.Estado
  comprobante_url?: string | null
  created_at?: Date | string
}

export type InscripcionUpdateWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  comprobante_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  evento?: Prisma.EventoUpdateOneRequiredWithoutInscripcionesNestedInput
}

export type InscripcionUncheckedUpdateWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  evento_id?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  comprobante_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionUncheckedUpdateManyWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  evento_id?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  comprobante_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionCreateManyEventoInput = {
  id?: string
  usuario_id: string
  estado?: $Enums.Estado
  comprobante_url?: string | null
  created_at?: Date | string
}

export type InscripcionUpdateWithoutEventoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  comprobante_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutInscripcionesNestedInput
}

export type InscripcionUncheckedUpdateWithoutEventoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuario_id?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  comprobante_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionUncheckedUpdateManyWithoutEventoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuario_id?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  comprobante_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type InscripcionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuario_id?: boolean
  evento_id?: boolean
  estado?: boolean
  comprobante_url?: boolean
  created_at?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  evento?: boolean | Prisma.EventoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inscripcion"]>

export type InscripcionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuario_id?: boolean
  evento_id?: boolean
  estado?: boolean
  comprobante_url?: boolean
  created_at?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  evento?: boolean | Prisma.EventoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inscripcion"]>

export type InscripcionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuario_id?: boolean
  evento_id?: boolean
  estado?: boolean
  comprobante_url?: boolean
  created_at?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  evento?: boolean | Prisma.EventoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inscripcion"]>

export type InscripcionSelectScalar = {
  id?: boolean
  usuario_id?: boolean
  evento_id?: boolean
  estado?: boolean
  comprobante_url?: boolean
  created_at?: boolean
}

export type InscripcionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "usuario_id" | "evento_id" | "estado" | "comprobante_url" | "created_at", ExtArgs["result"]["inscripcion"]>
export type InscripcionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  evento?: boolean | Prisma.EventoDefaultArgs<ExtArgs>
}
export type InscripcionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  evento?: boolean | Prisma.EventoDefaultArgs<ExtArgs>
}
export type InscripcionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  evento?: boolean | Prisma.EventoDefaultArgs<ExtArgs>
}

export type $InscripcionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Inscripcion"
  objects: {
    usuario: Prisma.$UsuarioPayload<ExtArgs>
    evento: Prisma.$EventoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    usuario_id: string
    evento_id: string
    estado: $Enums.Estado
    comprobante_url: string | null
    created_at: Date
  }, ExtArgs["result"]["inscripcion"]>
  composites: {}
}

export type InscripcionGetPayload<S extends boolean | null | undefined | InscripcionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InscripcionPayload, S>

export type InscripcionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InscripcionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InscripcionCountAggregateInputType | true
  }

export interface InscripcionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Inscripcion'], meta: { name: 'Inscripcion' } }
  /**
   * Find zero or one Inscripcion that matches the filter.
   * @param {InscripcionFindUniqueArgs} args - Arguments to find a Inscripcion
   * @example
   * // Get one Inscripcion
   * const inscripcion = await prisma.inscripcion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InscripcionFindUniqueArgs>(args: Prisma.SelectSubset<T, InscripcionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Inscripcion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InscripcionFindUniqueOrThrowArgs} args - Arguments to find a Inscripcion
   * @example
   * // Get one Inscripcion
   * const inscripcion = await prisma.inscripcion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InscripcionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InscripcionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Inscripcion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionFindFirstArgs} args - Arguments to find a Inscripcion
   * @example
   * // Get one Inscripcion
   * const inscripcion = await prisma.inscripcion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InscripcionFindFirstArgs>(args?: Prisma.SelectSubset<T, InscripcionFindFirstArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Inscripcion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionFindFirstOrThrowArgs} args - Arguments to find a Inscripcion
   * @example
   * // Get one Inscripcion
   * const inscripcion = await prisma.inscripcion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InscripcionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InscripcionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Inscripcions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Inscripcions
   * const inscripcions = await prisma.inscripcion.findMany()
   * 
   * // Get first 10 Inscripcions
   * const inscripcions = await prisma.inscripcion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const inscripcionWithIdOnly = await prisma.inscripcion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InscripcionFindManyArgs>(args?: Prisma.SelectSubset<T, InscripcionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Inscripcion.
   * @param {InscripcionCreateArgs} args - Arguments to create a Inscripcion.
   * @example
   * // Create one Inscripcion
   * const Inscripcion = await prisma.inscripcion.create({
   *   data: {
   *     // ... data to create a Inscripcion
   *   }
   * })
   * 
   */
  create<T extends InscripcionCreateArgs>(args: Prisma.SelectSubset<T, InscripcionCreateArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Inscripcions.
   * @param {InscripcionCreateManyArgs} args - Arguments to create many Inscripcions.
   * @example
   * // Create many Inscripcions
   * const inscripcion = await prisma.inscripcion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InscripcionCreateManyArgs>(args?: Prisma.SelectSubset<T, InscripcionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Inscripcions and returns the data saved in the database.
   * @param {InscripcionCreateManyAndReturnArgs} args - Arguments to create many Inscripcions.
   * @example
   * // Create many Inscripcions
   * const inscripcion = await prisma.inscripcion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Inscripcions and only return the `id`
   * const inscripcionWithIdOnly = await prisma.inscripcion.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InscripcionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InscripcionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Inscripcion.
   * @param {InscripcionDeleteArgs} args - Arguments to delete one Inscripcion.
   * @example
   * // Delete one Inscripcion
   * const Inscripcion = await prisma.inscripcion.delete({
   *   where: {
   *     // ... filter to delete one Inscripcion
   *   }
   * })
   * 
   */
  delete<T extends InscripcionDeleteArgs>(args: Prisma.SelectSubset<T, InscripcionDeleteArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Inscripcion.
   * @param {InscripcionUpdateArgs} args - Arguments to update one Inscripcion.
   * @example
   * // Update one Inscripcion
   * const inscripcion = await prisma.inscripcion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InscripcionUpdateArgs>(args: Prisma.SelectSubset<T, InscripcionUpdateArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Inscripcions.
   * @param {InscripcionDeleteManyArgs} args - Arguments to filter Inscripcions to delete.
   * @example
   * // Delete a few Inscripcions
   * const { count } = await prisma.inscripcion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InscripcionDeleteManyArgs>(args?: Prisma.SelectSubset<T, InscripcionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Inscripcions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Inscripcions
   * const inscripcion = await prisma.inscripcion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InscripcionUpdateManyArgs>(args: Prisma.SelectSubset<T, InscripcionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Inscripcions and returns the data updated in the database.
   * @param {InscripcionUpdateManyAndReturnArgs} args - Arguments to update many Inscripcions.
   * @example
   * // Update many Inscripcions
   * const inscripcion = await prisma.inscripcion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Inscripcions and only return the `id`
   * const inscripcionWithIdOnly = await prisma.inscripcion.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InscripcionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InscripcionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Inscripcion.
   * @param {InscripcionUpsertArgs} args - Arguments to update or create a Inscripcion.
   * @example
   * // Update or create a Inscripcion
   * const inscripcion = await prisma.inscripcion.upsert({
   *   create: {
   *     // ... data to create a Inscripcion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Inscripcion we want to update
   *   }
   * })
   */
  upsert<T extends InscripcionUpsertArgs>(args: Prisma.SelectSubset<T, InscripcionUpsertArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Inscripcions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionCountArgs} args - Arguments to filter Inscripcions to count.
   * @example
   * // Count the number of Inscripcions
   * const count = await prisma.inscripcion.count({
   *   where: {
   *     // ... the filter for the Inscripcions we want to count
   *   }
   * })
  **/
  count<T extends InscripcionCountArgs>(
    args?: Prisma.Subset<T, InscripcionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InscripcionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Inscripcion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InscripcionAggregateArgs>(args: Prisma.Subset<T, InscripcionAggregateArgs>): Prisma.PrismaPromise<GetInscripcionAggregateType<T>>

  /**
   * Group by Inscripcion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InscripcionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InscripcionGroupByArgs['orderBy'] }
      : { orderBy?: InscripcionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InscripcionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInscripcionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Inscripcion model
 */
readonly fields: InscripcionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Inscripcion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InscripcionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  usuario<T extends Prisma.UsuarioDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuarioDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  evento<T extends Prisma.EventoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventoDefaultArgs<ExtArgs>>): Prisma.Prisma__EventoClient<runtime.Types.Result.GetResult<Prisma.$EventoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Inscripcion model
 */
export interface InscripcionFieldRefs {
  readonly id: Prisma.FieldRef<"Inscripcion", 'String'>
  readonly usuario_id: Prisma.FieldRef<"Inscripcion", 'String'>
  readonly evento_id: Prisma.FieldRef<"Inscripcion", 'String'>
  readonly estado: Prisma.FieldRef<"Inscripcion", 'Estado'>
  readonly comprobante_url: Prisma.FieldRef<"Inscripcion", 'String'>
  readonly created_at: Prisma.FieldRef<"Inscripcion", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Inscripcion findUnique
 */
export type InscripcionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter, which Inscripcion to fetch.
   */
  where: Prisma.InscripcionWhereUniqueInput
}

/**
 * Inscripcion findUniqueOrThrow
 */
export type InscripcionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter, which Inscripcion to fetch.
   */
  where: Prisma.InscripcionWhereUniqueInput
}

/**
 * Inscripcion findFirst
 */
export type InscripcionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter, which Inscripcion to fetch.
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Inscripcions to fetch.
   */
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Inscripcions.
   */
  cursor?: Prisma.InscripcionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Inscripcions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Inscripcions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Inscripcions.
   */
  distinct?: Prisma.InscripcionScalarFieldEnum | Prisma.InscripcionScalarFieldEnum[]
}

/**
 * Inscripcion findFirstOrThrow
 */
export type InscripcionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter, which Inscripcion to fetch.
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Inscripcions to fetch.
   */
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Inscripcions.
   */
  cursor?: Prisma.InscripcionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Inscripcions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Inscripcions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Inscripcions.
   */
  distinct?: Prisma.InscripcionScalarFieldEnum | Prisma.InscripcionScalarFieldEnum[]
}

/**
 * Inscripcion findMany
 */
export type InscripcionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter, which Inscripcions to fetch.
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Inscripcions to fetch.
   */
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Inscripcions.
   */
  cursor?: Prisma.InscripcionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Inscripcions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Inscripcions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Inscripcions.
   */
  distinct?: Prisma.InscripcionScalarFieldEnum | Prisma.InscripcionScalarFieldEnum[]
}

/**
 * Inscripcion create
 */
export type InscripcionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * The data needed to create a Inscripcion.
   */
  data: Prisma.XOR<Prisma.InscripcionCreateInput, Prisma.InscripcionUncheckedCreateInput>
}

/**
 * Inscripcion createMany
 */
export type InscripcionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Inscripcions.
   */
  data: Prisma.InscripcionCreateManyInput | Prisma.InscripcionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Inscripcion createManyAndReturn
 */
export type InscripcionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * The data used to create many Inscripcions.
   */
  data: Prisma.InscripcionCreateManyInput | Prisma.InscripcionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Inscripcion update
 */
export type InscripcionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * The data needed to update a Inscripcion.
   */
  data: Prisma.XOR<Prisma.InscripcionUpdateInput, Prisma.InscripcionUncheckedUpdateInput>
  /**
   * Choose, which Inscripcion to update.
   */
  where: Prisma.InscripcionWhereUniqueInput
}

/**
 * Inscripcion updateMany
 */
export type InscripcionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Inscripcions.
   */
  data: Prisma.XOR<Prisma.InscripcionUpdateManyMutationInput, Prisma.InscripcionUncheckedUpdateManyInput>
  /**
   * Filter which Inscripcions to update
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * Limit how many Inscripcions to update.
   */
  limit?: number
}

/**
 * Inscripcion updateManyAndReturn
 */
export type InscripcionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * The data used to update Inscripcions.
   */
  data: Prisma.XOR<Prisma.InscripcionUpdateManyMutationInput, Prisma.InscripcionUncheckedUpdateManyInput>
  /**
   * Filter which Inscripcions to update
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * Limit how many Inscripcions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Inscripcion upsert
 */
export type InscripcionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * The filter to search for the Inscripcion to update in case it exists.
   */
  where: Prisma.InscripcionWhereUniqueInput
  /**
   * In case the Inscripcion found by the `where` argument doesn't exist, create a new Inscripcion with this data.
   */
  create: Prisma.XOR<Prisma.InscripcionCreateInput, Prisma.InscripcionUncheckedCreateInput>
  /**
   * In case the Inscripcion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InscripcionUpdateInput, Prisma.InscripcionUncheckedUpdateInput>
}

/**
 * Inscripcion delete
 */
export type InscripcionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter which Inscripcion to delete.
   */
  where: Prisma.InscripcionWhereUniqueInput
}

/**
 * Inscripcion deleteMany
 */
export type InscripcionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Inscripcions to delete
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * Limit how many Inscripcions to delete.
   */
  limit?: number
}

/**
 * Inscripcion without action
 */
export type InscripcionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
}
