
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Solicitud` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Solicitud
 * 
 */
export type SolicitudModel = runtime.Types.Result.DefaultSelection<Prisma.$SolicitudPayload>

export type AggregateSolicitud = {
  _count: SolicitudCountAggregateOutputType | null
  _min: SolicitudMinAggregateOutputType | null
  _max: SolicitudMaxAggregateOutputType | null
}

export type SolicitudMinAggregateOutputType = {
  id: string | null
  usuario_id: string | null
  pastor_id: string | null
  mensaje: string | null
  estado: $Enums.Estado | null
  fecha_solicitada: Date | null
  created_at: Date | null
}

export type SolicitudMaxAggregateOutputType = {
  id: string | null
  usuario_id: string | null
  pastor_id: string | null
  mensaje: string | null
  estado: $Enums.Estado | null
  fecha_solicitada: Date | null
  created_at: Date | null
}

export type SolicitudCountAggregateOutputType = {
  id: number
  usuario_id: number
  pastor_id: number
  mensaje: number
  estado: number
  fecha_solicitada: number
  created_at: number
  _all: number
}


export type SolicitudMinAggregateInputType = {
  id?: true
  usuario_id?: true
  pastor_id?: true
  mensaje?: true
  estado?: true
  fecha_solicitada?: true
  created_at?: true
}

export type SolicitudMaxAggregateInputType = {
  id?: true
  usuario_id?: true
  pastor_id?: true
  mensaje?: true
  estado?: true
  fecha_solicitada?: true
  created_at?: true
}

export type SolicitudCountAggregateInputType = {
  id?: true
  usuario_id?: true
  pastor_id?: true
  mensaje?: true
  estado?: true
  fecha_solicitada?: true
  created_at?: true
  _all?: true
}

export type SolicitudAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Solicitud to aggregate.
   */
  where?: Prisma.SolicitudWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Solicituds to fetch.
   */
  orderBy?: Prisma.SolicitudOrderByWithRelationInput | Prisma.SolicitudOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SolicitudWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Solicituds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Solicituds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Solicituds
  **/
  _count?: true | SolicitudCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SolicitudMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SolicitudMaxAggregateInputType
}

export type GetSolicitudAggregateType<T extends SolicitudAggregateArgs> = {
      [P in keyof T & keyof AggregateSolicitud]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSolicitud[P]>
    : Prisma.GetScalarType<T[P], AggregateSolicitud[P]>
}




export type SolicitudGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SolicitudWhereInput
  orderBy?: Prisma.SolicitudOrderByWithAggregationInput | Prisma.SolicitudOrderByWithAggregationInput[]
  by: Prisma.SolicitudScalarFieldEnum[] | Prisma.SolicitudScalarFieldEnum
  having?: Prisma.SolicitudScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SolicitudCountAggregateInputType | true
  _min?: SolicitudMinAggregateInputType
  _max?: SolicitudMaxAggregateInputType
}

export type SolicitudGroupByOutputType = {
  id: string
  usuario_id: string
  pastor_id: string
  mensaje: string
  estado: $Enums.Estado
  fecha_solicitada: Date
  created_at: Date
  _count: SolicitudCountAggregateOutputType | null
  _min: SolicitudMinAggregateOutputType | null
  _max: SolicitudMaxAggregateOutputType | null
}

export type GetSolicitudGroupByPayload<T extends SolicitudGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SolicitudGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SolicitudGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SolicitudGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SolicitudGroupByOutputType[P]>
      }
    >
  >



export type SolicitudWhereInput = {
  AND?: Prisma.SolicitudWhereInput | Prisma.SolicitudWhereInput[]
  OR?: Prisma.SolicitudWhereInput[]
  NOT?: Prisma.SolicitudWhereInput | Prisma.SolicitudWhereInput[]
  id?: Prisma.StringFilter<"Solicitud"> | string
  usuario_id?: Prisma.StringFilter<"Solicitud"> | string
  pastor_id?: Prisma.StringFilter<"Solicitud"> | string
  mensaje?: Prisma.StringFilter<"Solicitud"> | string
  estado?: Prisma.EnumEstadoFilter<"Solicitud"> | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFilter<"Solicitud"> | Date | string
  created_at?: Prisma.DateTimeFilter<"Solicitud"> | Date | string
  usuario?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  pastor?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
}

export type SolicitudOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  pastor_id?: Prisma.SortOrder
  mensaje?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  fecha_solicitada?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  usuario?: Prisma.UsuarioOrderByWithRelationInput
  pastor?: Prisma.UsuarioOrderByWithRelationInput
}

export type SolicitudWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SolicitudWhereInput | Prisma.SolicitudWhereInput[]
  OR?: Prisma.SolicitudWhereInput[]
  NOT?: Prisma.SolicitudWhereInput | Prisma.SolicitudWhereInput[]
  usuario_id?: Prisma.StringFilter<"Solicitud"> | string
  pastor_id?: Prisma.StringFilter<"Solicitud"> | string
  mensaje?: Prisma.StringFilter<"Solicitud"> | string
  estado?: Prisma.EnumEstadoFilter<"Solicitud"> | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFilter<"Solicitud"> | Date | string
  created_at?: Prisma.DateTimeFilter<"Solicitud"> | Date | string
  usuario?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  pastor?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
}, "id">

export type SolicitudOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  pastor_id?: Prisma.SortOrder
  mensaje?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  fecha_solicitada?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.SolicitudCountOrderByAggregateInput
  _max?: Prisma.SolicitudMaxOrderByAggregateInput
  _min?: Prisma.SolicitudMinOrderByAggregateInput
}

export type SolicitudScalarWhereWithAggregatesInput = {
  AND?: Prisma.SolicitudScalarWhereWithAggregatesInput | Prisma.SolicitudScalarWhereWithAggregatesInput[]
  OR?: Prisma.SolicitudScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SolicitudScalarWhereWithAggregatesInput | Prisma.SolicitudScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Solicitud"> | string
  usuario_id?: Prisma.StringWithAggregatesFilter<"Solicitud"> | string
  pastor_id?: Prisma.StringWithAggregatesFilter<"Solicitud"> | string
  mensaje?: Prisma.StringWithAggregatesFilter<"Solicitud"> | string
  estado?: Prisma.EnumEstadoWithAggregatesFilter<"Solicitud"> | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeWithAggregatesFilter<"Solicitud"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Solicitud"> | Date | string
}

export type SolicitudCreateInput = {
  id?: string
  mensaje: string
  estado?: $Enums.Estado
  fecha_solicitada: Date | string
  created_at?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutSolicitudesInput
  pastor: Prisma.UsuarioCreateNestedOneWithoutPastor_solicitudesInput
}

export type SolicitudUncheckedCreateInput = {
  id?: string
  usuario_id: string
  pastor_id: string
  mensaje: string
  estado?: $Enums.Estado
  fecha_solicitada: Date | string
  created_at?: Date | string
}

export type SolicitudUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mensaje?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutSolicitudesNestedInput
  pastor?: Prisma.UsuarioUpdateOneRequiredWithoutPastor_solicitudesNestedInput
}

export type SolicitudUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuario_id?: Prisma.StringFieldUpdateOperationsInput | string
  pastor_id?: Prisma.StringFieldUpdateOperationsInput | string
  mensaje?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SolicitudCreateManyInput = {
  id?: string
  usuario_id: string
  pastor_id: string
  mensaje: string
  estado?: $Enums.Estado
  fecha_solicitada: Date | string
  created_at?: Date | string
}

export type SolicitudUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mensaje?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SolicitudUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuario_id?: Prisma.StringFieldUpdateOperationsInput | string
  pastor_id?: Prisma.StringFieldUpdateOperationsInput | string
  mensaje?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SolicitudListRelationFilter = {
  every?: Prisma.SolicitudWhereInput
  some?: Prisma.SolicitudWhereInput
  none?: Prisma.SolicitudWhereInput
}

export type SolicitudOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SolicitudCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  pastor_id?: Prisma.SortOrder
  mensaje?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  fecha_solicitada?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type SolicitudMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  pastor_id?: Prisma.SortOrder
  mensaje?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  fecha_solicitada?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type SolicitudMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  pastor_id?: Prisma.SortOrder
  mensaje?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  fecha_solicitada?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type SolicitudCreateNestedManyWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.SolicitudCreateWithoutUsuarioInput, Prisma.SolicitudUncheckedCreateWithoutUsuarioInput> | Prisma.SolicitudCreateWithoutUsuarioInput[] | Prisma.SolicitudUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.SolicitudCreateOrConnectWithoutUsuarioInput | Prisma.SolicitudCreateOrConnectWithoutUsuarioInput[]
  createMany?: Prisma.SolicitudCreateManyUsuarioInputEnvelope
  connect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
}

export type SolicitudCreateNestedManyWithoutPastorInput = {
  create?: Prisma.XOR<Prisma.SolicitudCreateWithoutPastorInput, Prisma.SolicitudUncheckedCreateWithoutPastorInput> | Prisma.SolicitudCreateWithoutPastorInput[] | Prisma.SolicitudUncheckedCreateWithoutPastorInput[]
  connectOrCreate?: Prisma.SolicitudCreateOrConnectWithoutPastorInput | Prisma.SolicitudCreateOrConnectWithoutPastorInput[]
  createMany?: Prisma.SolicitudCreateManyPastorInputEnvelope
  connect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
}

export type SolicitudUncheckedCreateNestedManyWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.SolicitudCreateWithoutUsuarioInput, Prisma.SolicitudUncheckedCreateWithoutUsuarioInput> | Prisma.SolicitudCreateWithoutUsuarioInput[] | Prisma.SolicitudUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.SolicitudCreateOrConnectWithoutUsuarioInput | Prisma.SolicitudCreateOrConnectWithoutUsuarioInput[]
  createMany?: Prisma.SolicitudCreateManyUsuarioInputEnvelope
  connect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
}

export type SolicitudUncheckedCreateNestedManyWithoutPastorInput = {
  create?: Prisma.XOR<Prisma.SolicitudCreateWithoutPastorInput, Prisma.SolicitudUncheckedCreateWithoutPastorInput> | Prisma.SolicitudCreateWithoutPastorInput[] | Prisma.SolicitudUncheckedCreateWithoutPastorInput[]
  connectOrCreate?: Prisma.SolicitudCreateOrConnectWithoutPastorInput | Prisma.SolicitudCreateOrConnectWithoutPastorInput[]
  createMany?: Prisma.SolicitudCreateManyPastorInputEnvelope
  connect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
}

export type SolicitudUpdateManyWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.SolicitudCreateWithoutUsuarioInput, Prisma.SolicitudUncheckedCreateWithoutUsuarioInput> | Prisma.SolicitudCreateWithoutUsuarioInput[] | Prisma.SolicitudUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.SolicitudCreateOrConnectWithoutUsuarioInput | Prisma.SolicitudCreateOrConnectWithoutUsuarioInput[]
  upsert?: Prisma.SolicitudUpsertWithWhereUniqueWithoutUsuarioInput | Prisma.SolicitudUpsertWithWhereUniqueWithoutUsuarioInput[]
  createMany?: Prisma.SolicitudCreateManyUsuarioInputEnvelope
  set?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  disconnect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  delete?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  connect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  update?: Prisma.SolicitudUpdateWithWhereUniqueWithoutUsuarioInput | Prisma.SolicitudUpdateWithWhereUniqueWithoutUsuarioInput[]
  updateMany?: Prisma.SolicitudUpdateManyWithWhereWithoutUsuarioInput | Prisma.SolicitudUpdateManyWithWhereWithoutUsuarioInput[]
  deleteMany?: Prisma.SolicitudScalarWhereInput | Prisma.SolicitudScalarWhereInput[]
}

export type SolicitudUpdateManyWithoutPastorNestedInput = {
  create?: Prisma.XOR<Prisma.SolicitudCreateWithoutPastorInput, Prisma.SolicitudUncheckedCreateWithoutPastorInput> | Prisma.SolicitudCreateWithoutPastorInput[] | Prisma.SolicitudUncheckedCreateWithoutPastorInput[]
  connectOrCreate?: Prisma.SolicitudCreateOrConnectWithoutPastorInput | Prisma.SolicitudCreateOrConnectWithoutPastorInput[]
  upsert?: Prisma.SolicitudUpsertWithWhereUniqueWithoutPastorInput | Prisma.SolicitudUpsertWithWhereUniqueWithoutPastorInput[]
  createMany?: Prisma.SolicitudCreateManyPastorInputEnvelope
  set?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  disconnect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  delete?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  connect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  update?: Prisma.SolicitudUpdateWithWhereUniqueWithoutPastorInput | Prisma.SolicitudUpdateWithWhereUniqueWithoutPastorInput[]
  updateMany?: Prisma.SolicitudUpdateManyWithWhereWithoutPastorInput | Prisma.SolicitudUpdateManyWithWhereWithoutPastorInput[]
  deleteMany?: Prisma.SolicitudScalarWhereInput | Prisma.SolicitudScalarWhereInput[]
}

export type SolicitudUncheckedUpdateManyWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.SolicitudCreateWithoutUsuarioInput, Prisma.SolicitudUncheckedCreateWithoutUsuarioInput> | Prisma.SolicitudCreateWithoutUsuarioInput[] | Prisma.SolicitudUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.SolicitudCreateOrConnectWithoutUsuarioInput | Prisma.SolicitudCreateOrConnectWithoutUsuarioInput[]
  upsert?: Prisma.SolicitudUpsertWithWhereUniqueWithoutUsuarioInput | Prisma.SolicitudUpsertWithWhereUniqueWithoutUsuarioInput[]
  createMany?: Prisma.SolicitudCreateManyUsuarioInputEnvelope
  set?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  disconnect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  delete?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  connect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  update?: Prisma.SolicitudUpdateWithWhereUniqueWithoutUsuarioInput | Prisma.SolicitudUpdateWithWhereUniqueWithoutUsuarioInput[]
  updateMany?: Prisma.SolicitudUpdateManyWithWhereWithoutUsuarioInput | Prisma.SolicitudUpdateManyWithWhereWithoutUsuarioInput[]
  deleteMany?: Prisma.SolicitudScalarWhereInput | Prisma.SolicitudScalarWhereInput[]
}

export type SolicitudUncheckedUpdateManyWithoutPastorNestedInput = {
  create?: Prisma.XOR<Prisma.SolicitudCreateWithoutPastorInput, Prisma.SolicitudUncheckedCreateWithoutPastorInput> | Prisma.SolicitudCreateWithoutPastorInput[] | Prisma.SolicitudUncheckedCreateWithoutPastorInput[]
  connectOrCreate?: Prisma.SolicitudCreateOrConnectWithoutPastorInput | Prisma.SolicitudCreateOrConnectWithoutPastorInput[]
  upsert?: Prisma.SolicitudUpsertWithWhereUniqueWithoutPastorInput | Prisma.SolicitudUpsertWithWhereUniqueWithoutPastorInput[]
  createMany?: Prisma.SolicitudCreateManyPastorInputEnvelope
  set?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  disconnect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  delete?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  connect?: Prisma.SolicitudWhereUniqueInput | Prisma.SolicitudWhereUniqueInput[]
  update?: Prisma.SolicitudUpdateWithWhereUniqueWithoutPastorInput | Prisma.SolicitudUpdateWithWhereUniqueWithoutPastorInput[]
  updateMany?: Prisma.SolicitudUpdateManyWithWhereWithoutPastorInput | Prisma.SolicitudUpdateManyWithWhereWithoutPastorInput[]
  deleteMany?: Prisma.SolicitudScalarWhereInput | Prisma.SolicitudScalarWhereInput[]
}

export type SolicitudCreateWithoutUsuarioInput = {
  id?: string
  mensaje: string
  estado?: $Enums.Estado
  fecha_solicitada: Date | string
  created_at?: Date | string
  pastor: Prisma.UsuarioCreateNestedOneWithoutPastor_solicitudesInput
}

export type SolicitudUncheckedCreateWithoutUsuarioInput = {
  id?: string
  pastor_id: string
  mensaje: string
  estado?: $Enums.Estado
  fecha_solicitada: Date | string
  created_at?: Date | string
}

export type SolicitudCreateOrConnectWithoutUsuarioInput = {
  where: Prisma.SolicitudWhereUniqueInput
  create: Prisma.XOR<Prisma.SolicitudCreateWithoutUsuarioInput, Prisma.SolicitudUncheckedCreateWithoutUsuarioInput>
}

export type SolicitudCreateManyUsuarioInputEnvelope = {
  data: Prisma.SolicitudCreateManyUsuarioInput | Prisma.SolicitudCreateManyUsuarioInput[]
  skipDuplicates?: boolean
}

export type SolicitudCreateWithoutPastorInput = {
  id?: string
  mensaje: string
  estado?: $Enums.Estado
  fecha_solicitada: Date | string
  created_at?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutSolicitudesInput
}

export type SolicitudUncheckedCreateWithoutPastorInput = {
  id?: string
  usuario_id: string
  mensaje: string
  estado?: $Enums.Estado
  fecha_solicitada: Date | string
  created_at?: Date | string
}

export type SolicitudCreateOrConnectWithoutPastorInput = {
  where: Prisma.SolicitudWhereUniqueInput
  create: Prisma.XOR<Prisma.SolicitudCreateWithoutPastorInput, Prisma.SolicitudUncheckedCreateWithoutPastorInput>
}

export type SolicitudCreateManyPastorInputEnvelope = {
  data: Prisma.SolicitudCreateManyPastorInput | Prisma.SolicitudCreateManyPastorInput[]
  skipDuplicates?: boolean
}

export type SolicitudUpsertWithWhereUniqueWithoutUsuarioInput = {
  where: Prisma.SolicitudWhereUniqueInput
  update: Prisma.XOR<Prisma.SolicitudUpdateWithoutUsuarioInput, Prisma.SolicitudUncheckedUpdateWithoutUsuarioInput>
  create: Prisma.XOR<Prisma.SolicitudCreateWithoutUsuarioInput, Prisma.SolicitudUncheckedCreateWithoutUsuarioInput>
}

export type SolicitudUpdateWithWhereUniqueWithoutUsuarioInput = {
  where: Prisma.SolicitudWhereUniqueInput
  data: Prisma.XOR<Prisma.SolicitudUpdateWithoutUsuarioInput, Prisma.SolicitudUncheckedUpdateWithoutUsuarioInput>
}

export type SolicitudUpdateManyWithWhereWithoutUsuarioInput = {
  where: Prisma.SolicitudScalarWhereInput
  data: Prisma.XOR<Prisma.SolicitudUpdateManyMutationInput, Prisma.SolicitudUncheckedUpdateManyWithoutUsuarioInput>
}

export type SolicitudScalarWhereInput = {
  AND?: Prisma.SolicitudScalarWhereInput | Prisma.SolicitudScalarWhereInput[]
  OR?: Prisma.SolicitudScalarWhereInput[]
  NOT?: Prisma.SolicitudScalarWhereInput | Prisma.SolicitudScalarWhereInput[]
  id?: Prisma.StringFilter<"Solicitud"> | string
  usuario_id?: Prisma.StringFilter<"Solicitud"> | string
  pastor_id?: Prisma.StringFilter<"Solicitud"> | string
  mensaje?: Prisma.StringFilter<"Solicitud"> | string
  estado?: Prisma.EnumEstadoFilter<"Solicitud"> | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFilter<"Solicitud"> | Date | string
  created_at?: Prisma.DateTimeFilter<"Solicitud"> | Date | string
}

export type SolicitudUpsertWithWhereUniqueWithoutPastorInput = {
  where: Prisma.SolicitudWhereUniqueInput
  update: Prisma.XOR<Prisma.SolicitudUpdateWithoutPastorInput, Prisma.SolicitudUncheckedUpdateWithoutPastorInput>
  create: Prisma.XOR<Prisma.SolicitudCreateWithoutPastorInput, Prisma.SolicitudUncheckedCreateWithoutPastorInput>
}

export type SolicitudUpdateWithWhereUniqueWithoutPastorInput = {
  where: Prisma.SolicitudWhereUniqueInput
  data: Prisma.XOR<Prisma.SolicitudUpdateWithoutPastorInput, Prisma.SolicitudUncheckedUpdateWithoutPastorInput>
}

export type SolicitudUpdateManyWithWhereWithoutPastorInput = {
  where: Prisma.SolicitudScalarWhereInput
  data: Prisma.XOR<Prisma.SolicitudUpdateManyMutationInput, Prisma.SolicitudUncheckedUpdateManyWithoutPastorInput>
}

export type SolicitudCreateManyUsuarioInput = {
  id?: string
  pastor_id: string
  mensaje: string
  estado?: $Enums.Estado
  fecha_solicitada: Date | string
  created_at?: Date | string
}

export type SolicitudCreateManyPastorInput = {
  id?: string
  usuario_id: string
  mensaje: string
  estado?: $Enums.Estado
  fecha_solicitada: Date | string
  created_at?: Date | string
}

export type SolicitudUpdateWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mensaje?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pastor?: Prisma.UsuarioUpdateOneRequiredWithoutPastor_solicitudesNestedInput
}

export type SolicitudUncheckedUpdateWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pastor_id?: Prisma.StringFieldUpdateOperationsInput | string
  mensaje?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SolicitudUncheckedUpdateManyWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pastor_id?: Prisma.StringFieldUpdateOperationsInput | string
  mensaje?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SolicitudUpdateWithoutPastorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mensaje?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutSolicitudesNestedInput
}

export type SolicitudUncheckedUpdateWithoutPastorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuario_id?: Prisma.StringFieldUpdateOperationsInput | string
  mensaje?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SolicitudUncheckedUpdateManyWithoutPastorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuario_id?: Prisma.StringFieldUpdateOperationsInput | string
  mensaje?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.EnumEstadoFieldUpdateOperationsInput | $Enums.Estado
  fecha_solicitada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SolicitudSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuario_id?: boolean
  pastor_id?: boolean
  mensaje?: boolean
  estado?: boolean
  fecha_solicitada?: boolean
  created_at?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  pastor?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}, ExtArgs["result"]["solicitud"]>

export type SolicitudSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuario_id?: boolean
  pastor_id?: boolean
  mensaje?: boolean
  estado?: boolean
  fecha_solicitada?: boolean
  created_at?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  pastor?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}, ExtArgs["result"]["solicitud"]>

export type SolicitudSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuario_id?: boolean
  pastor_id?: boolean
  mensaje?: boolean
  estado?: boolean
  fecha_solicitada?: boolean
  created_at?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  pastor?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}, ExtArgs["result"]["solicitud"]>

export type SolicitudSelectScalar = {
  id?: boolean
  usuario_id?: boolean
  pastor_id?: boolean
  mensaje?: boolean
  estado?: boolean
  fecha_solicitada?: boolean
  created_at?: boolean
}

export type SolicitudOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "usuario_id" | "pastor_id" | "mensaje" | "estado" | "fecha_solicitada" | "created_at", ExtArgs["result"]["solicitud"]>
export type SolicitudInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  pastor?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}
export type SolicitudIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  pastor?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}
export type SolicitudIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  pastor?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}

export type $SolicitudPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Solicitud"
  objects: {
    usuario: Prisma.$UsuarioPayload<ExtArgs>
    pastor: Prisma.$UsuarioPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    usuario_id: string
    pastor_id: string
    mensaje: string
    estado: $Enums.Estado
    fecha_solicitada: Date
    created_at: Date
  }, ExtArgs["result"]["solicitud"]>
  composites: {}
}

export type SolicitudGetPayload<S extends boolean | null | undefined | SolicitudDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SolicitudPayload, S>

export type SolicitudCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SolicitudFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SolicitudCountAggregateInputType | true
  }

export interface SolicitudDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Solicitud'], meta: { name: 'Solicitud' } }
  /**
   * Find zero or one Solicitud that matches the filter.
   * @param {SolicitudFindUniqueArgs} args - Arguments to find a Solicitud
   * @example
   * // Get one Solicitud
   * const solicitud = await prisma.solicitud.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SolicitudFindUniqueArgs>(args: Prisma.SelectSubset<T, SolicitudFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SolicitudClient<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Solicitud that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SolicitudFindUniqueOrThrowArgs} args - Arguments to find a Solicitud
   * @example
   * // Get one Solicitud
   * const solicitud = await prisma.solicitud.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SolicitudFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SolicitudFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SolicitudClient<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Solicitud that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudFindFirstArgs} args - Arguments to find a Solicitud
   * @example
   * // Get one Solicitud
   * const solicitud = await prisma.solicitud.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SolicitudFindFirstArgs>(args?: Prisma.SelectSubset<T, SolicitudFindFirstArgs<ExtArgs>>): Prisma.Prisma__SolicitudClient<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Solicitud that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudFindFirstOrThrowArgs} args - Arguments to find a Solicitud
   * @example
   * // Get one Solicitud
   * const solicitud = await prisma.solicitud.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SolicitudFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SolicitudFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SolicitudClient<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Solicituds that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Solicituds
   * const solicituds = await prisma.solicitud.findMany()
   * 
   * // Get first 10 Solicituds
   * const solicituds = await prisma.solicitud.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const solicitudWithIdOnly = await prisma.solicitud.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SolicitudFindManyArgs>(args?: Prisma.SelectSubset<T, SolicitudFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Solicitud.
   * @param {SolicitudCreateArgs} args - Arguments to create a Solicitud.
   * @example
   * // Create one Solicitud
   * const Solicitud = await prisma.solicitud.create({
   *   data: {
   *     // ... data to create a Solicitud
   *   }
   * })
   * 
   */
  create<T extends SolicitudCreateArgs>(args: Prisma.SelectSubset<T, SolicitudCreateArgs<ExtArgs>>): Prisma.Prisma__SolicitudClient<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Solicituds.
   * @param {SolicitudCreateManyArgs} args - Arguments to create many Solicituds.
   * @example
   * // Create many Solicituds
   * const solicitud = await prisma.solicitud.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SolicitudCreateManyArgs>(args?: Prisma.SelectSubset<T, SolicitudCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Solicituds and returns the data saved in the database.
   * @param {SolicitudCreateManyAndReturnArgs} args - Arguments to create many Solicituds.
   * @example
   * // Create many Solicituds
   * const solicitud = await prisma.solicitud.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Solicituds and only return the `id`
   * const solicitudWithIdOnly = await prisma.solicitud.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SolicitudCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SolicitudCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Solicitud.
   * @param {SolicitudDeleteArgs} args - Arguments to delete one Solicitud.
   * @example
   * // Delete one Solicitud
   * const Solicitud = await prisma.solicitud.delete({
   *   where: {
   *     // ... filter to delete one Solicitud
   *   }
   * })
   * 
   */
  delete<T extends SolicitudDeleteArgs>(args: Prisma.SelectSubset<T, SolicitudDeleteArgs<ExtArgs>>): Prisma.Prisma__SolicitudClient<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Solicitud.
   * @param {SolicitudUpdateArgs} args - Arguments to update one Solicitud.
   * @example
   * // Update one Solicitud
   * const solicitud = await prisma.solicitud.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SolicitudUpdateArgs>(args: Prisma.SelectSubset<T, SolicitudUpdateArgs<ExtArgs>>): Prisma.Prisma__SolicitudClient<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Solicituds.
   * @param {SolicitudDeleteManyArgs} args - Arguments to filter Solicituds to delete.
   * @example
   * // Delete a few Solicituds
   * const { count } = await prisma.solicitud.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SolicitudDeleteManyArgs>(args?: Prisma.SelectSubset<T, SolicitudDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Solicituds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Solicituds
   * const solicitud = await prisma.solicitud.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SolicitudUpdateManyArgs>(args: Prisma.SelectSubset<T, SolicitudUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Solicituds and returns the data updated in the database.
   * @param {SolicitudUpdateManyAndReturnArgs} args - Arguments to update many Solicituds.
   * @example
   * // Update many Solicituds
   * const solicitud = await prisma.solicitud.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Solicituds and only return the `id`
   * const solicitudWithIdOnly = await prisma.solicitud.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SolicitudUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SolicitudUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Solicitud.
   * @param {SolicitudUpsertArgs} args - Arguments to update or create a Solicitud.
   * @example
   * // Update or create a Solicitud
   * const solicitud = await prisma.solicitud.upsert({
   *   create: {
   *     // ... data to create a Solicitud
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Solicitud we want to update
   *   }
   * })
   */
  upsert<T extends SolicitudUpsertArgs>(args: Prisma.SelectSubset<T, SolicitudUpsertArgs<ExtArgs>>): Prisma.Prisma__SolicitudClient<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Solicituds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudCountArgs} args - Arguments to filter Solicituds to count.
   * @example
   * // Count the number of Solicituds
   * const count = await prisma.solicitud.count({
   *   where: {
   *     // ... the filter for the Solicituds we want to count
   *   }
   * })
  **/
  count<T extends SolicitudCountArgs>(
    args?: Prisma.Subset<T, SolicitudCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SolicitudCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Solicitud.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SolicitudAggregateArgs>(args: Prisma.Subset<T, SolicitudAggregateArgs>): Prisma.PrismaPromise<GetSolicitudAggregateType<T>>

  /**
   * Group by Solicitud.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SolicitudGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SolicitudGroupByArgs['orderBy'] }
      : { orderBy?: SolicitudGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SolicitudGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSolicitudGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Solicitud model
 */
readonly fields: SolicitudFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Solicitud.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SolicitudClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  usuario<T extends Prisma.UsuarioDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuarioDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  pastor<T extends Prisma.UsuarioDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuarioDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Solicitud model
 */
export interface SolicitudFieldRefs {
  readonly id: Prisma.FieldRef<"Solicitud", 'String'>
  readonly usuario_id: Prisma.FieldRef<"Solicitud", 'String'>
  readonly pastor_id: Prisma.FieldRef<"Solicitud", 'String'>
  readonly mensaje: Prisma.FieldRef<"Solicitud", 'String'>
  readonly estado: Prisma.FieldRef<"Solicitud", 'Estado'>
  readonly fecha_solicitada: Prisma.FieldRef<"Solicitud", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"Solicitud", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Solicitud findUnique
 */
export type SolicitudFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  /**
   * Filter, which Solicitud to fetch.
   */
  where: Prisma.SolicitudWhereUniqueInput
}

/**
 * Solicitud findUniqueOrThrow
 */
export type SolicitudFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  /**
   * Filter, which Solicitud to fetch.
   */
  where: Prisma.SolicitudWhereUniqueInput
}

/**
 * Solicitud findFirst
 */
export type SolicitudFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  /**
   * Filter, which Solicitud to fetch.
   */
  where?: Prisma.SolicitudWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Solicituds to fetch.
   */
  orderBy?: Prisma.SolicitudOrderByWithRelationInput | Prisma.SolicitudOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Solicituds.
   */
  cursor?: Prisma.SolicitudWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Solicituds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Solicituds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Solicituds.
   */
  distinct?: Prisma.SolicitudScalarFieldEnum | Prisma.SolicitudScalarFieldEnum[]
}

/**
 * Solicitud findFirstOrThrow
 */
export type SolicitudFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  /**
   * Filter, which Solicitud to fetch.
   */
  where?: Prisma.SolicitudWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Solicituds to fetch.
   */
  orderBy?: Prisma.SolicitudOrderByWithRelationInput | Prisma.SolicitudOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Solicituds.
   */
  cursor?: Prisma.SolicitudWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Solicituds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Solicituds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Solicituds.
   */
  distinct?: Prisma.SolicitudScalarFieldEnum | Prisma.SolicitudScalarFieldEnum[]
}

/**
 * Solicitud findMany
 */
export type SolicitudFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  /**
   * Filter, which Solicituds to fetch.
   */
  where?: Prisma.SolicitudWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Solicituds to fetch.
   */
  orderBy?: Prisma.SolicitudOrderByWithRelationInput | Prisma.SolicitudOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Solicituds.
   */
  cursor?: Prisma.SolicitudWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Solicituds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Solicituds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Solicituds.
   */
  distinct?: Prisma.SolicitudScalarFieldEnum | Prisma.SolicitudScalarFieldEnum[]
}

/**
 * Solicitud create
 */
export type SolicitudCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  /**
   * The data needed to create a Solicitud.
   */
  data: Prisma.XOR<Prisma.SolicitudCreateInput, Prisma.SolicitudUncheckedCreateInput>
}

/**
 * Solicitud createMany
 */
export type SolicitudCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Solicituds.
   */
  data: Prisma.SolicitudCreateManyInput | Prisma.SolicitudCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Solicitud createManyAndReturn
 */
export type SolicitudCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * The data used to create many Solicituds.
   */
  data: Prisma.SolicitudCreateManyInput | Prisma.SolicitudCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Solicitud update
 */
export type SolicitudUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  /**
   * The data needed to update a Solicitud.
   */
  data: Prisma.XOR<Prisma.SolicitudUpdateInput, Prisma.SolicitudUncheckedUpdateInput>
  /**
   * Choose, which Solicitud to update.
   */
  where: Prisma.SolicitudWhereUniqueInput
}

/**
 * Solicitud updateMany
 */
export type SolicitudUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Solicituds.
   */
  data: Prisma.XOR<Prisma.SolicitudUpdateManyMutationInput, Prisma.SolicitudUncheckedUpdateManyInput>
  /**
   * Filter which Solicituds to update
   */
  where?: Prisma.SolicitudWhereInput
  /**
   * Limit how many Solicituds to update.
   */
  limit?: number
}

/**
 * Solicitud updateManyAndReturn
 */
export type SolicitudUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * The data used to update Solicituds.
   */
  data: Prisma.XOR<Prisma.SolicitudUpdateManyMutationInput, Prisma.SolicitudUncheckedUpdateManyInput>
  /**
   * Filter which Solicituds to update
   */
  where?: Prisma.SolicitudWhereInput
  /**
   * Limit how many Solicituds to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Solicitud upsert
 */
export type SolicitudUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  /**
   * The filter to search for the Solicitud to update in case it exists.
   */
  where: Prisma.SolicitudWhereUniqueInput
  /**
   * In case the Solicitud found by the `where` argument doesn't exist, create a new Solicitud with this data.
   */
  create: Prisma.XOR<Prisma.SolicitudCreateInput, Prisma.SolicitudUncheckedCreateInput>
  /**
   * In case the Solicitud was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SolicitudUpdateInput, Prisma.SolicitudUncheckedUpdateInput>
}

/**
 * Solicitud delete
 */
export type SolicitudDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  /**
   * Filter which Solicitud to delete.
   */
  where: Prisma.SolicitudWhereUniqueInput
}

/**
 * Solicitud deleteMany
 */
export type SolicitudDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Solicituds to delete
   */
  where?: Prisma.SolicitudWhereInput
  /**
   * Limit how many Solicituds to delete.
   */
  limit?: number
}

/**
 * Solicitud without action
 */
export type SolicitudDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
}
