
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Usuario` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Usuario
 * 
 */
export type UsuarioModel = runtime.Types.Result.DefaultSelection<Prisma.$UsuarioPayload>

export type AggregateUsuario = {
  _count: UsuarioCountAggregateOutputType | null
  _min: UsuarioMinAggregateOutputType | null
  _max: UsuarioMaxAggregateOutputType | null
}

export type UsuarioMinAggregateOutputType = {
  id: string | null
  nombre: string | null
  email: string | null
  password: string | null
  rut: string | null
  direccion: string | null
  telefono: string | null
  telefono_emergencia: string | null
  fecha_nacimiento: Date | null
  foto_url: string | null
  iglesia_id: string | null
  rol_id: string | null
  created_at: Date | null
}

export type UsuarioMaxAggregateOutputType = {
  id: string | null
  nombre: string | null
  email: string | null
  password: string | null
  rut: string | null
  direccion: string | null
  telefono: string | null
  telefono_emergencia: string | null
  fecha_nacimiento: Date | null
  foto_url: string | null
  iglesia_id: string | null
  rol_id: string | null
  created_at: Date | null
}

export type UsuarioCountAggregateOutputType = {
  id: number
  nombre: number
  email: number
  password: number
  rut: number
  direccion: number
  telefono: number
  telefono_emergencia: number
  fecha_nacimiento: number
  foto_url: number
  iglesia_id: number
  rol_id: number
  created_at: number
  _all: number
}


export type UsuarioMinAggregateInputType = {
  id?: true
  nombre?: true
  email?: true
  password?: true
  rut?: true
  direccion?: true
  telefono?: true
  telefono_emergencia?: true
  fecha_nacimiento?: true
  foto_url?: true
  iglesia_id?: true
  rol_id?: true
  created_at?: true
}

export type UsuarioMaxAggregateInputType = {
  id?: true
  nombre?: true
  email?: true
  password?: true
  rut?: true
  direccion?: true
  telefono?: true
  telefono_emergencia?: true
  fecha_nacimiento?: true
  foto_url?: true
  iglesia_id?: true
  rol_id?: true
  created_at?: true
}

export type UsuarioCountAggregateInputType = {
  id?: true
  nombre?: true
  email?: true
  password?: true
  rut?: true
  direccion?: true
  telefono?: true
  telefono_emergencia?: true
  fecha_nacimiento?: true
  foto_url?: true
  iglesia_id?: true
  rol_id?: true
  created_at?: true
  _all?: true
}

export type UsuarioAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Usuario to aggregate.
   */
  where?: Prisma.UsuarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usuarios to fetch.
   */
  orderBy?: Prisma.UsuarioOrderByWithRelationInput | Prisma.UsuarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UsuarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usuarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usuarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Usuarios
  **/
  _count?: true | UsuarioCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UsuarioMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UsuarioMaxAggregateInputType
}

export type GetUsuarioAggregateType<T extends UsuarioAggregateArgs> = {
      [P in keyof T & keyof AggregateUsuario]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUsuario[P]>
    : Prisma.GetScalarType<T[P], AggregateUsuario[P]>
}




export type UsuarioGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UsuarioWhereInput
  orderBy?: Prisma.UsuarioOrderByWithAggregationInput | Prisma.UsuarioOrderByWithAggregationInput[]
  by: Prisma.UsuarioScalarFieldEnum[] | Prisma.UsuarioScalarFieldEnum
  having?: Prisma.UsuarioScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UsuarioCountAggregateInputType | true
  _min?: UsuarioMinAggregateInputType
  _max?: UsuarioMaxAggregateInputType
}

export type UsuarioGroupByOutputType = {
  id: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date
  foto_url: string
  iglesia_id: string
  rol_id: string
  created_at: Date
  _count: UsuarioCountAggregateOutputType | null
  _min: UsuarioMinAggregateOutputType | null
  _max: UsuarioMaxAggregateOutputType | null
}

export type GetUsuarioGroupByPayload<T extends UsuarioGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UsuarioGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UsuarioGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UsuarioGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UsuarioGroupByOutputType[P]>
      }
    >
  >



export type UsuarioWhereInput = {
  AND?: Prisma.UsuarioWhereInput | Prisma.UsuarioWhereInput[]
  OR?: Prisma.UsuarioWhereInput[]
  NOT?: Prisma.UsuarioWhereInput | Prisma.UsuarioWhereInput[]
  id?: Prisma.StringFilter<"Usuario"> | string
  nombre?: Prisma.StringFilter<"Usuario"> | string
  email?: Prisma.StringFilter<"Usuario"> | string
  password?: Prisma.StringFilter<"Usuario"> | string
  rut?: Prisma.StringFilter<"Usuario"> | string
  direccion?: Prisma.StringFilter<"Usuario"> | string
  telefono?: Prisma.StringFilter<"Usuario"> | string
  telefono_emergencia?: Prisma.StringFilter<"Usuario"> | string
  fecha_nacimiento?: Prisma.DateTimeFilter<"Usuario"> | Date | string
  foto_url?: Prisma.StringFilter<"Usuario"> | string
  iglesia_id?: Prisma.StringFilter<"Usuario"> | string
  rol_id?: Prisma.StringFilter<"Usuario"> | string
  created_at?: Prisma.DateTimeFilter<"Usuario"> | Date | string
  iglesia?: Prisma.XOR<Prisma.IglesiaScalarRelationFilter, Prisma.IglesiaWhereInput>
  rol?: Prisma.XOR<Prisma.RolScalarRelationFilter, Prisma.RolWhereInput>
  inscripciones?: Prisma.InscripcionListRelationFilter
  solicitudes?: Prisma.SolicitudListRelationFilter
  pastor_solicitudes?: Prisma.SolicitudListRelationFilter
}

export type UsuarioOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  rut?: Prisma.SortOrder
  direccion?: Prisma.SortOrder
  telefono?: Prisma.SortOrder
  telefono_emergencia?: Prisma.SortOrder
  fecha_nacimiento?: Prisma.SortOrder
  foto_url?: Prisma.SortOrder
  iglesia_id?: Prisma.SortOrder
  rol_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  iglesia?: Prisma.IglesiaOrderByWithRelationInput
  rol?: Prisma.RolOrderByWithRelationInput
  inscripciones?: Prisma.InscripcionOrderByRelationAggregateInput
  solicitudes?: Prisma.SolicitudOrderByRelationAggregateInput
  pastor_solicitudes?: Prisma.SolicitudOrderByRelationAggregateInput
}

export type UsuarioWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  rut?: string
  AND?: Prisma.UsuarioWhereInput | Prisma.UsuarioWhereInput[]
  OR?: Prisma.UsuarioWhereInput[]
  NOT?: Prisma.UsuarioWhereInput | Prisma.UsuarioWhereInput[]
  nombre?: Prisma.StringFilter<"Usuario"> | string
  password?: Prisma.StringFilter<"Usuario"> | string
  direccion?: Prisma.StringFilter<"Usuario"> | string
  telefono?: Prisma.StringFilter<"Usuario"> | string
  telefono_emergencia?: Prisma.StringFilter<"Usuario"> | string
  fecha_nacimiento?: Prisma.DateTimeFilter<"Usuario"> | Date | string
  foto_url?: Prisma.StringFilter<"Usuario"> | string
  iglesia_id?: Prisma.StringFilter<"Usuario"> | string
  rol_id?: Prisma.StringFilter<"Usuario"> | string
  created_at?: Prisma.DateTimeFilter<"Usuario"> | Date | string
  iglesia?: Prisma.XOR<Prisma.IglesiaScalarRelationFilter, Prisma.IglesiaWhereInput>
  rol?: Prisma.XOR<Prisma.RolScalarRelationFilter, Prisma.RolWhereInput>
  inscripciones?: Prisma.InscripcionListRelationFilter
  solicitudes?: Prisma.SolicitudListRelationFilter
  pastor_solicitudes?: Prisma.SolicitudListRelationFilter
}, "id" | "email" | "rut">

export type UsuarioOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  rut?: Prisma.SortOrder
  direccion?: Prisma.SortOrder
  telefono?: Prisma.SortOrder
  telefono_emergencia?: Prisma.SortOrder
  fecha_nacimiento?: Prisma.SortOrder
  foto_url?: Prisma.SortOrder
  iglesia_id?: Prisma.SortOrder
  rol_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.UsuarioCountOrderByAggregateInput
  _max?: Prisma.UsuarioMaxOrderByAggregateInput
  _min?: Prisma.UsuarioMinOrderByAggregateInput
}

export type UsuarioScalarWhereWithAggregatesInput = {
  AND?: Prisma.UsuarioScalarWhereWithAggregatesInput | Prisma.UsuarioScalarWhereWithAggregatesInput[]
  OR?: Prisma.UsuarioScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UsuarioScalarWhereWithAggregatesInput | Prisma.UsuarioScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  nombre?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  email?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  password?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  rut?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  direccion?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  telefono?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  telefono_emergencia?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  fecha_nacimiento?: Prisma.DateTimeWithAggregatesFilter<"Usuario"> | Date | string
  foto_url?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  iglesia_id?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  rol_id?: Prisma.StringWithAggregatesFilter<"Usuario"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Usuario"> | Date | string
}

export type UsuarioCreateInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  created_at?: Date | string
  iglesia: Prisma.IglesiaCreateNestedOneWithoutUsuariosInput
  rol: Prisma.RolCreateNestedOneWithoutUsuariosInput
  inscripciones?: Prisma.InscripcionCreateNestedManyWithoutUsuarioInput
  solicitudes?: Prisma.SolicitudCreateNestedManyWithoutUsuarioInput
  pastor_solicitudes?: Prisma.SolicitudCreateNestedManyWithoutPastorInput
}

export type UsuarioUncheckedCreateInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  iglesia_id: string
  rol_id: string
  created_at?: Date | string
  inscripciones?: Prisma.InscripcionUncheckedCreateNestedManyWithoutUsuarioInput
  solicitudes?: Prisma.SolicitudUncheckedCreateNestedManyWithoutUsuarioInput
  pastor_solicitudes?: Prisma.SolicitudUncheckedCreateNestedManyWithoutPastorInput
}

export type UsuarioUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iglesia?: Prisma.IglesiaUpdateOneRequiredWithoutUsuariosNestedInput
  rol?: Prisma.RolUpdateOneRequiredWithoutUsuariosNestedInput
  inscripciones?: Prisma.InscripcionUpdateManyWithoutUsuarioNestedInput
  solicitudes?: Prisma.SolicitudUpdateManyWithoutUsuarioNestedInput
  pastor_solicitudes?: Prisma.SolicitudUpdateManyWithoutPastorNestedInput
}

export type UsuarioUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  iglesia_id?: Prisma.StringFieldUpdateOperationsInput | string
  rol_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  inscripciones?: Prisma.InscripcionUncheckedUpdateManyWithoutUsuarioNestedInput
  solicitudes?: Prisma.SolicitudUncheckedUpdateManyWithoutUsuarioNestedInput
  pastor_solicitudes?: Prisma.SolicitudUncheckedUpdateManyWithoutPastorNestedInput
}

export type UsuarioCreateManyInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  iglesia_id: string
  rol_id: string
  created_at?: Date | string
}

export type UsuarioUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsuarioUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  iglesia_id?: Prisma.StringFieldUpdateOperationsInput | string
  rol_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsuarioListRelationFilter = {
  every?: Prisma.UsuarioWhereInput
  some?: Prisma.UsuarioWhereInput
  none?: Prisma.UsuarioWhereInput
}

export type UsuarioOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UsuarioCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  rut?: Prisma.SortOrder
  direccion?: Prisma.SortOrder
  telefono?: Prisma.SortOrder
  telefono_emergencia?: Prisma.SortOrder
  fecha_nacimiento?: Prisma.SortOrder
  foto_url?: Prisma.SortOrder
  iglesia_id?: Prisma.SortOrder
  rol_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type UsuarioMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  rut?: Prisma.SortOrder
  direccion?: Prisma.SortOrder
  telefono?: Prisma.SortOrder
  telefono_emergencia?: Prisma.SortOrder
  fecha_nacimiento?: Prisma.SortOrder
  foto_url?: Prisma.SortOrder
  iglesia_id?: Prisma.SortOrder
  rol_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type UsuarioMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  rut?: Prisma.SortOrder
  direccion?: Prisma.SortOrder
  telefono?: Prisma.SortOrder
  telefono_emergencia?: Prisma.SortOrder
  fecha_nacimiento?: Prisma.SortOrder
  foto_url?: Prisma.SortOrder
  iglesia_id?: Prisma.SortOrder
  rol_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type UsuarioScalarRelationFilter = {
  is?: Prisma.UsuarioWhereInput
  isNot?: Prisma.UsuarioWhereInput
}

export type UsuarioCreateNestedManyWithoutIglesiaInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutIglesiaInput, Prisma.UsuarioUncheckedCreateWithoutIglesiaInput> | Prisma.UsuarioCreateWithoutIglesiaInput[] | Prisma.UsuarioUncheckedCreateWithoutIglesiaInput[]
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutIglesiaInput | Prisma.UsuarioCreateOrConnectWithoutIglesiaInput[]
  createMany?: Prisma.UsuarioCreateManyIglesiaInputEnvelope
  connect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
}

export type UsuarioUncheckedCreateNestedManyWithoutIglesiaInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutIglesiaInput, Prisma.UsuarioUncheckedCreateWithoutIglesiaInput> | Prisma.UsuarioCreateWithoutIglesiaInput[] | Prisma.UsuarioUncheckedCreateWithoutIglesiaInput[]
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutIglesiaInput | Prisma.UsuarioCreateOrConnectWithoutIglesiaInput[]
  createMany?: Prisma.UsuarioCreateManyIglesiaInputEnvelope
  connect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
}

export type UsuarioUpdateManyWithoutIglesiaNestedInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutIglesiaInput, Prisma.UsuarioUncheckedCreateWithoutIglesiaInput> | Prisma.UsuarioCreateWithoutIglesiaInput[] | Prisma.UsuarioUncheckedCreateWithoutIglesiaInput[]
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutIglesiaInput | Prisma.UsuarioCreateOrConnectWithoutIglesiaInput[]
  upsert?: Prisma.UsuarioUpsertWithWhereUniqueWithoutIglesiaInput | Prisma.UsuarioUpsertWithWhereUniqueWithoutIglesiaInput[]
  createMany?: Prisma.UsuarioCreateManyIglesiaInputEnvelope
  set?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  disconnect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  delete?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  connect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  update?: Prisma.UsuarioUpdateWithWhereUniqueWithoutIglesiaInput | Prisma.UsuarioUpdateWithWhereUniqueWithoutIglesiaInput[]
  updateMany?: Prisma.UsuarioUpdateManyWithWhereWithoutIglesiaInput | Prisma.UsuarioUpdateManyWithWhereWithoutIglesiaInput[]
  deleteMany?: Prisma.UsuarioScalarWhereInput | Prisma.UsuarioScalarWhereInput[]
}

export type UsuarioUncheckedUpdateManyWithoutIglesiaNestedInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutIglesiaInput, Prisma.UsuarioUncheckedCreateWithoutIglesiaInput> | Prisma.UsuarioCreateWithoutIglesiaInput[] | Prisma.UsuarioUncheckedCreateWithoutIglesiaInput[]
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutIglesiaInput | Prisma.UsuarioCreateOrConnectWithoutIglesiaInput[]
  upsert?: Prisma.UsuarioUpsertWithWhereUniqueWithoutIglesiaInput | Prisma.UsuarioUpsertWithWhereUniqueWithoutIglesiaInput[]
  createMany?: Prisma.UsuarioCreateManyIglesiaInputEnvelope
  set?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  disconnect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  delete?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  connect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  update?: Prisma.UsuarioUpdateWithWhereUniqueWithoutIglesiaInput | Prisma.UsuarioUpdateWithWhereUniqueWithoutIglesiaInput[]
  updateMany?: Prisma.UsuarioUpdateManyWithWhereWithoutIglesiaInput | Prisma.UsuarioUpdateManyWithWhereWithoutIglesiaInput[]
  deleteMany?: Prisma.UsuarioScalarWhereInput | Prisma.UsuarioScalarWhereInput[]
}

export type UsuarioCreateNestedManyWithoutRolInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutRolInput, Prisma.UsuarioUncheckedCreateWithoutRolInput> | Prisma.UsuarioCreateWithoutRolInput[] | Prisma.UsuarioUncheckedCreateWithoutRolInput[]
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutRolInput | Prisma.UsuarioCreateOrConnectWithoutRolInput[]
  createMany?: Prisma.UsuarioCreateManyRolInputEnvelope
  connect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
}

export type UsuarioUncheckedCreateNestedManyWithoutRolInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutRolInput, Prisma.UsuarioUncheckedCreateWithoutRolInput> | Prisma.UsuarioCreateWithoutRolInput[] | Prisma.UsuarioUncheckedCreateWithoutRolInput[]
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutRolInput | Prisma.UsuarioCreateOrConnectWithoutRolInput[]
  createMany?: Prisma.UsuarioCreateManyRolInputEnvelope
  connect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
}

export type UsuarioUpdateManyWithoutRolNestedInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutRolInput, Prisma.UsuarioUncheckedCreateWithoutRolInput> | Prisma.UsuarioCreateWithoutRolInput[] | Prisma.UsuarioUncheckedCreateWithoutRolInput[]
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutRolInput | Prisma.UsuarioCreateOrConnectWithoutRolInput[]
  upsert?: Prisma.UsuarioUpsertWithWhereUniqueWithoutRolInput | Prisma.UsuarioUpsertWithWhereUniqueWithoutRolInput[]
  createMany?: Prisma.UsuarioCreateManyRolInputEnvelope
  set?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  disconnect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  delete?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  connect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  update?: Prisma.UsuarioUpdateWithWhereUniqueWithoutRolInput | Prisma.UsuarioUpdateWithWhereUniqueWithoutRolInput[]
  updateMany?: Prisma.UsuarioUpdateManyWithWhereWithoutRolInput | Prisma.UsuarioUpdateManyWithWhereWithoutRolInput[]
  deleteMany?: Prisma.UsuarioScalarWhereInput | Prisma.UsuarioScalarWhereInput[]
}

export type UsuarioUncheckedUpdateManyWithoutRolNestedInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutRolInput, Prisma.UsuarioUncheckedCreateWithoutRolInput> | Prisma.UsuarioCreateWithoutRolInput[] | Prisma.UsuarioUncheckedCreateWithoutRolInput[]
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutRolInput | Prisma.UsuarioCreateOrConnectWithoutRolInput[]
  upsert?: Prisma.UsuarioUpsertWithWhereUniqueWithoutRolInput | Prisma.UsuarioUpsertWithWhereUniqueWithoutRolInput[]
  createMany?: Prisma.UsuarioCreateManyRolInputEnvelope
  set?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  disconnect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  delete?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  connect?: Prisma.UsuarioWhereUniqueInput | Prisma.UsuarioWhereUniqueInput[]
  update?: Prisma.UsuarioUpdateWithWhereUniqueWithoutRolInput | Prisma.UsuarioUpdateWithWhereUniqueWithoutRolInput[]
  updateMany?: Prisma.UsuarioUpdateManyWithWhereWithoutRolInput | Prisma.UsuarioUpdateManyWithWhereWithoutRolInput[]
  deleteMany?: Prisma.UsuarioScalarWhereInput | Prisma.UsuarioScalarWhereInput[]
}

export type UsuarioCreateNestedOneWithoutInscripcionesInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutInscripcionesInput, Prisma.UsuarioUncheckedCreateWithoutInscripcionesInput>
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutInscripcionesInput
  connect?: Prisma.UsuarioWhereUniqueInput
}

export type UsuarioUpdateOneRequiredWithoutInscripcionesNestedInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutInscripcionesInput, Prisma.UsuarioUncheckedCreateWithoutInscripcionesInput>
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutInscripcionesInput
  upsert?: Prisma.UsuarioUpsertWithoutInscripcionesInput
  connect?: Prisma.UsuarioWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsuarioUpdateToOneWithWhereWithoutInscripcionesInput, Prisma.UsuarioUpdateWithoutInscripcionesInput>, Prisma.UsuarioUncheckedUpdateWithoutInscripcionesInput>
}

export type UsuarioCreateNestedOneWithoutSolicitudesInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutSolicitudesInput, Prisma.UsuarioUncheckedCreateWithoutSolicitudesInput>
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutSolicitudesInput
  connect?: Prisma.UsuarioWhereUniqueInput
}

export type UsuarioCreateNestedOneWithoutPastor_solicitudesInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutPastor_solicitudesInput, Prisma.UsuarioUncheckedCreateWithoutPastor_solicitudesInput>
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutPastor_solicitudesInput
  connect?: Prisma.UsuarioWhereUniqueInput
}

export type UsuarioUpdateOneRequiredWithoutSolicitudesNestedInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutSolicitudesInput, Prisma.UsuarioUncheckedCreateWithoutSolicitudesInput>
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutSolicitudesInput
  upsert?: Prisma.UsuarioUpsertWithoutSolicitudesInput
  connect?: Prisma.UsuarioWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsuarioUpdateToOneWithWhereWithoutSolicitudesInput, Prisma.UsuarioUpdateWithoutSolicitudesInput>, Prisma.UsuarioUncheckedUpdateWithoutSolicitudesInput>
}

export type UsuarioUpdateOneRequiredWithoutPastor_solicitudesNestedInput = {
  create?: Prisma.XOR<Prisma.UsuarioCreateWithoutPastor_solicitudesInput, Prisma.UsuarioUncheckedCreateWithoutPastor_solicitudesInput>
  connectOrCreate?: Prisma.UsuarioCreateOrConnectWithoutPastor_solicitudesInput
  upsert?: Prisma.UsuarioUpsertWithoutPastor_solicitudesInput
  connect?: Prisma.UsuarioWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsuarioUpdateToOneWithWhereWithoutPastor_solicitudesInput, Prisma.UsuarioUpdateWithoutPastor_solicitudesInput>, Prisma.UsuarioUncheckedUpdateWithoutPastor_solicitudesInput>
}

export type UsuarioCreateWithoutIglesiaInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  created_at?: Date | string
  rol: Prisma.RolCreateNestedOneWithoutUsuariosInput
  inscripciones?: Prisma.InscripcionCreateNestedManyWithoutUsuarioInput
  solicitudes?: Prisma.SolicitudCreateNestedManyWithoutUsuarioInput
  pastor_solicitudes?: Prisma.SolicitudCreateNestedManyWithoutPastorInput
}

export type UsuarioUncheckedCreateWithoutIglesiaInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  rol_id: string
  created_at?: Date | string
  inscripciones?: Prisma.InscripcionUncheckedCreateNestedManyWithoutUsuarioInput
  solicitudes?: Prisma.SolicitudUncheckedCreateNestedManyWithoutUsuarioInput
  pastor_solicitudes?: Prisma.SolicitudUncheckedCreateNestedManyWithoutPastorInput
}

export type UsuarioCreateOrConnectWithoutIglesiaInput = {
  where: Prisma.UsuarioWhereUniqueInput
  create: Prisma.XOR<Prisma.UsuarioCreateWithoutIglesiaInput, Prisma.UsuarioUncheckedCreateWithoutIglesiaInput>
}

export type UsuarioCreateManyIglesiaInputEnvelope = {
  data: Prisma.UsuarioCreateManyIglesiaInput | Prisma.UsuarioCreateManyIglesiaInput[]
  skipDuplicates?: boolean
}

export type UsuarioUpsertWithWhereUniqueWithoutIglesiaInput = {
  where: Prisma.UsuarioWhereUniqueInput
  update: Prisma.XOR<Prisma.UsuarioUpdateWithoutIglesiaInput, Prisma.UsuarioUncheckedUpdateWithoutIglesiaInput>
  create: Prisma.XOR<Prisma.UsuarioCreateWithoutIglesiaInput, Prisma.UsuarioUncheckedCreateWithoutIglesiaInput>
}

export type UsuarioUpdateWithWhereUniqueWithoutIglesiaInput = {
  where: Prisma.UsuarioWhereUniqueInput
  data: Prisma.XOR<Prisma.UsuarioUpdateWithoutIglesiaInput, Prisma.UsuarioUncheckedUpdateWithoutIglesiaInput>
}

export type UsuarioUpdateManyWithWhereWithoutIglesiaInput = {
  where: Prisma.UsuarioScalarWhereInput
  data: Prisma.XOR<Prisma.UsuarioUpdateManyMutationInput, Prisma.UsuarioUncheckedUpdateManyWithoutIglesiaInput>
}

export type UsuarioScalarWhereInput = {
  AND?: Prisma.UsuarioScalarWhereInput | Prisma.UsuarioScalarWhereInput[]
  OR?: Prisma.UsuarioScalarWhereInput[]
  NOT?: Prisma.UsuarioScalarWhereInput | Prisma.UsuarioScalarWhereInput[]
  id?: Prisma.StringFilter<"Usuario"> | string
  nombre?: Prisma.StringFilter<"Usuario"> | string
  email?: Prisma.StringFilter<"Usuario"> | string
  password?: Prisma.StringFilter<"Usuario"> | string
  rut?: Prisma.StringFilter<"Usuario"> | string
  direccion?: Prisma.StringFilter<"Usuario"> | string
  telefono?: Prisma.StringFilter<"Usuario"> | string
  telefono_emergencia?: Prisma.StringFilter<"Usuario"> | string
  fecha_nacimiento?: Prisma.DateTimeFilter<"Usuario"> | Date | string
  foto_url?: Prisma.StringFilter<"Usuario"> | string
  iglesia_id?: Prisma.StringFilter<"Usuario"> | string
  rol_id?: Prisma.StringFilter<"Usuario"> | string
  created_at?: Prisma.DateTimeFilter<"Usuario"> | Date | string
}

export type UsuarioCreateWithoutRolInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  created_at?: Date | string
  iglesia: Prisma.IglesiaCreateNestedOneWithoutUsuariosInput
  inscripciones?: Prisma.InscripcionCreateNestedManyWithoutUsuarioInput
  solicitudes?: Prisma.SolicitudCreateNestedManyWithoutUsuarioInput
  pastor_solicitudes?: Prisma.SolicitudCreateNestedManyWithoutPastorInput
}

export type UsuarioUncheckedCreateWithoutRolInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  iglesia_id: string
  created_at?: Date | string
  inscripciones?: Prisma.InscripcionUncheckedCreateNestedManyWithoutUsuarioInput
  solicitudes?: Prisma.SolicitudUncheckedCreateNestedManyWithoutUsuarioInput
  pastor_solicitudes?: Prisma.SolicitudUncheckedCreateNestedManyWithoutPastorInput
}

export type UsuarioCreateOrConnectWithoutRolInput = {
  where: Prisma.UsuarioWhereUniqueInput
  create: Prisma.XOR<Prisma.UsuarioCreateWithoutRolInput, Prisma.UsuarioUncheckedCreateWithoutRolInput>
}

export type UsuarioCreateManyRolInputEnvelope = {
  data: Prisma.UsuarioCreateManyRolInput | Prisma.UsuarioCreateManyRolInput[]
  skipDuplicates?: boolean
}

export type UsuarioUpsertWithWhereUniqueWithoutRolInput = {
  where: Prisma.UsuarioWhereUniqueInput
  update: Prisma.XOR<Prisma.UsuarioUpdateWithoutRolInput, Prisma.UsuarioUncheckedUpdateWithoutRolInput>
  create: Prisma.XOR<Prisma.UsuarioCreateWithoutRolInput, Prisma.UsuarioUncheckedCreateWithoutRolInput>
}

export type UsuarioUpdateWithWhereUniqueWithoutRolInput = {
  where: Prisma.UsuarioWhereUniqueInput
  data: Prisma.XOR<Prisma.UsuarioUpdateWithoutRolInput, Prisma.UsuarioUncheckedUpdateWithoutRolInput>
}

export type UsuarioUpdateManyWithWhereWithoutRolInput = {
  where: Prisma.UsuarioScalarWhereInput
  data: Prisma.XOR<Prisma.UsuarioUpdateManyMutationInput, Prisma.UsuarioUncheckedUpdateManyWithoutRolInput>
}

export type UsuarioCreateWithoutInscripcionesInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  created_at?: Date | string
  iglesia: Prisma.IglesiaCreateNestedOneWithoutUsuariosInput
  rol: Prisma.RolCreateNestedOneWithoutUsuariosInput
  solicitudes?: Prisma.SolicitudCreateNestedManyWithoutUsuarioInput
  pastor_solicitudes?: Prisma.SolicitudCreateNestedManyWithoutPastorInput
}

export type UsuarioUncheckedCreateWithoutInscripcionesInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  iglesia_id: string
  rol_id: string
  created_at?: Date | string
  solicitudes?: Prisma.SolicitudUncheckedCreateNestedManyWithoutUsuarioInput
  pastor_solicitudes?: Prisma.SolicitudUncheckedCreateNestedManyWithoutPastorInput
}

export type UsuarioCreateOrConnectWithoutInscripcionesInput = {
  where: Prisma.UsuarioWhereUniqueInput
  create: Prisma.XOR<Prisma.UsuarioCreateWithoutInscripcionesInput, Prisma.UsuarioUncheckedCreateWithoutInscripcionesInput>
}

export type UsuarioUpsertWithoutInscripcionesInput = {
  update: Prisma.XOR<Prisma.UsuarioUpdateWithoutInscripcionesInput, Prisma.UsuarioUncheckedUpdateWithoutInscripcionesInput>
  create: Prisma.XOR<Prisma.UsuarioCreateWithoutInscripcionesInput, Prisma.UsuarioUncheckedCreateWithoutInscripcionesInput>
  where?: Prisma.UsuarioWhereInput
}

export type UsuarioUpdateToOneWithWhereWithoutInscripcionesInput = {
  where?: Prisma.UsuarioWhereInput
  data: Prisma.XOR<Prisma.UsuarioUpdateWithoutInscripcionesInput, Prisma.UsuarioUncheckedUpdateWithoutInscripcionesInput>
}

export type UsuarioUpdateWithoutInscripcionesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iglesia?: Prisma.IglesiaUpdateOneRequiredWithoutUsuariosNestedInput
  rol?: Prisma.RolUpdateOneRequiredWithoutUsuariosNestedInput
  solicitudes?: Prisma.SolicitudUpdateManyWithoutUsuarioNestedInput
  pastor_solicitudes?: Prisma.SolicitudUpdateManyWithoutPastorNestedInput
}

export type UsuarioUncheckedUpdateWithoutInscripcionesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  iglesia_id?: Prisma.StringFieldUpdateOperationsInput | string
  rol_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  solicitudes?: Prisma.SolicitudUncheckedUpdateManyWithoutUsuarioNestedInput
  pastor_solicitudes?: Prisma.SolicitudUncheckedUpdateManyWithoutPastorNestedInput
}

export type UsuarioCreateWithoutSolicitudesInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  created_at?: Date | string
  iglesia: Prisma.IglesiaCreateNestedOneWithoutUsuariosInput
  rol: Prisma.RolCreateNestedOneWithoutUsuariosInput
  inscripciones?: Prisma.InscripcionCreateNestedManyWithoutUsuarioInput
  pastor_solicitudes?: Prisma.SolicitudCreateNestedManyWithoutPastorInput
}

export type UsuarioUncheckedCreateWithoutSolicitudesInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  iglesia_id: string
  rol_id: string
  created_at?: Date | string
  inscripciones?: Prisma.InscripcionUncheckedCreateNestedManyWithoutUsuarioInput
  pastor_solicitudes?: Prisma.SolicitudUncheckedCreateNestedManyWithoutPastorInput
}

export type UsuarioCreateOrConnectWithoutSolicitudesInput = {
  where: Prisma.UsuarioWhereUniqueInput
  create: Prisma.XOR<Prisma.UsuarioCreateWithoutSolicitudesInput, Prisma.UsuarioUncheckedCreateWithoutSolicitudesInput>
}

export type UsuarioCreateWithoutPastor_solicitudesInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  created_at?: Date | string
  iglesia: Prisma.IglesiaCreateNestedOneWithoutUsuariosInput
  rol: Prisma.RolCreateNestedOneWithoutUsuariosInput
  inscripciones?: Prisma.InscripcionCreateNestedManyWithoutUsuarioInput
  solicitudes?: Prisma.SolicitudCreateNestedManyWithoutUsuarioInput
}

export type UsuarioUncheckedCreateWithoutPastor_solicitudesInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  iglesia_id: string
  rol_id: string
  created_at?: Date | string
  inscripciones?: Prisma.InscripcionUncheckedCreateNestedManyWithoutUsuarioInput
  solicitudes?: Prisma.SolicitudUncheckedCreateNestedManyWithoutUsuarioInput
}

export type UsuarioCreateOrConnectWithoutPastor_solicitudesInput = {
  where: Prisma.UsuarioWhereUniqueInput
  create: Prisma.XOR<Prisma.UsuarioCreateWithoutPastor_solicitudesInput, Prisma.UsuarioUncheckedCreateWithoutPastor_solicitudesInput>
}

export type UsuarioUpsertWithoutSolicitudesInput = {
  update: Prisma.XOR<Prisma.UsuarioUpdateWithoutSolicitudesInput, Prisma.UsuarioUncheckedUpdateWithoutSolicitudesInput>
  create: Prisma.XOR<Prisma.UsuarioCreateWithoutSolicitudesInput, Prisma.UsuarioUncheckedCreateWithoutSolicitudesInput>
  where?: Prisma.UsuarioWhereInput
}

export type UsuarioUpdateToOneWithWhereWithoutSolicitudesInput = {
  where?: Prisma.UsuarioWhereInput
  data: Prisma.XOR<Prisma.UsuarioUpdateWithoutSolicitudesInput, Prisma.UsuarioUncheckedUpdateWithoutSolicitudesInput>
}

export type UsuarioUpdateWithoutSolicitudesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iglesia?: Prisma.IglesiaUpdateOneRequiredWithoutUsuariosNestedInput
  rol?: Prisma.RolUpdateOneRequiredWithoutUsuariosNestedInput
  inscripciones?: Prisma.InscripcionUpdateManyWithoutUsuarioNestedInput
  pastor_solicitudes?: Prisma.SolicitudUpdateManyWithoutPastorNestedInput
}

export type UsuarioUncheckedUpdateWithoutSolicitudesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  iglesia_id?: Prisma.StringFieldUpdateOperationsInput | string
  rol_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  inscripciones?: Prisma.InscripcionUncheckedUpdateManyWithoutUsuarioNestedInput
  pastor_solicitudes?: Prisma.SolicitudUncheckedUpdateManyWithoutPastorNestedInput
}

export type UsuarioUpsertWithoutPastor_solicitudesInput = {
  update: Prisma.XOR<Prisma.UsuarioUpdateWithoutPastor_solicitudesInput, Prisma.UsuarioUncheckedUpdateWithoutPastor_solicitudesInput>
  create: Prisma.XOR<Prisma.UsuarioCreateWithoutPastor_solicitudesInput, Prisma.UsuarioUncheckedCreateWithoutPastor_solicitudesInput>
  where?: Prisma.UsuarioWhereInput
}

export type UsuarioUpdateToOneWithWhereWithoutPastor_solicitudesInput = {
  where?: Prisma.UsuarioWhereInput
  data: Prisma.XOR<Prisma.UsuarioUpdateWithoutPastor_solicitudesInput, Prisma.UsuarioUncheckedUpdateWithoutPastor_solicitudesInput>
}

export type UsuarioUpdateWithoutPastor_solicitudesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iglesia?: Prisma.IglesiaUpdateOneRequiredWithoutUsuariosNestedInput
  rol?: Prisma.RolUpdateOneRequiredWithoutUsuariosNestedInput
  inscripciones?: Prisma.InscripcionUpdateManyWithoutUsuarioNestedInput
  solicitudes?: Prisma.SolicitudUpdateManyWithoutUsuarioNestedInput
}

export type UsuarioUncheckedUpdateWithoutPastor_solicitudesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  iglesia_id?: Prisma.StringFieldUpdateOperationsInput | string
  rol_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  inscripciones?: Prisma.InscripcionUncheckedUpdateManyWithoutUsuarioNestedInput
  solicitudes?: Prisma.SolicitudUncheckedUpdateManyWithoutUsuarioNestedInput
}

export type UsuarioCreateManyIglesiaInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  rol_id: string
  created_at?: Date | string
}

export type UsuarioUpdateWithoutIglesiaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rol?: Prisma.RolUpdateOneRequiredWithoutUsuariosNestedInput
  inscripciones?: Prisma.InscripcionUpdateManyWithoutUsuarioNestedInput
  solicitudes?: Prisma.SolicitudUpdateManyWithoutUsuarioNestedInput
  pastor_solicitudes?: Prisma.SolicitudUpdateManyWithoutPastorNestedInput
}

export type UsuarioUncheckedUpdateWithoutIglesiaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  rol_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  inscripciones?: Prisma.InscripcionUncheckedUpdateManyWithoutUsuarioNestedInput
  solicitudes?: Prisma.SolicitudUncheckedUpdateManyWithoutUsuarioNestedInput
  pastor_solicitudes?: Prisma.SolicitudUncheckedUpdateManyWithoutPastorNestedInput
}

export type UsuarioUncheckedUpdateManyWithoutIglesiaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  rol_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsuarioCreateManyRolInput = {
  id?: string
  nombre: string
  email: string
  password: string
  rut: string
  direccion: string
  telefono: string
  telefono_emergencia: string
  fecha_nacimiento: Date | string
  foto_url: string
  iglesia_id: string
  created_at?: Date | string
}

export type UsuarioUpdateWithoutRolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  iglesia?: Prisma.IglesiaUpdateOneRequiredWithoutUsuariosNestedInput
  inscripciones?: Prisma.InscripcionUpdateManyWithoutUsuarioNestedInput
  solicitudes?: Prisma.SolicitudUpdateManyWithoutUsuarioNestedInput
  pastor_solicitudes?: Prisma.SolicitudUpdateManyWithoutPastorNestedInput
}

export type UsuarioUncheckedUpdateWithoutRolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  iglesia_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  inscripciones?: Prisma.InscripcionUncheckedUpdateManyWithoutUsuarioNestedInput
  solicitudes?: Prisma.SolicitudUncheckedUpdateManyWithoutUsuarioNestedInput
  pastor_solicitudes?: Prisma.SolicitudUncheckedUpdateManyWithoutPastorNestedInput
}

export type UsuarioUncheckedUpdateManyWithoutRolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rut?: Prisma.StringFieldUpdateOperationsInput | string
  direccion?: Prisma.StringFieldUpdateOperationsInput | string
  telefono?: Prisma.StringFieldUpdateOperationsInput | string
  telefono_emergencia?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_nacimiento?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  foto_url?: Prisma.StringFieldUpdateOperationsInput | string
  iglesia_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type UsuarioCountOutputType
 */

export type UsuarioCountOutputType = {
  inscripciones: number
  solicitudes: number
  pastor_solicitudes: number
}

export type UsuarioCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inscripciones?: boolean | UsuarioCountOutputTypeCountInscripcionesArgs
  solicitudes?: boolean | UsuarioCountOutputTypeCountSolicitudesArgs
  pastor_solicitudes?: boolean | UsuarioCountOutputTypeCountPastor_solicitudesArgs
}

/**
 * UsuarioCountOutputType without action
 */
export type UsuarioCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsuarioCountOutputType
   */
  select?: Prisma.UsuarioCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UsuarioCountOutputType without action
 */
export type UsuarioCountOutputTypeCountInscripcionesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InscripcionWhereInput
}

/**
 * UsuarioCountOutputType without action
 */
export type UsuarioCountOutputTypeCountSolicitudesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SolicitudWhereInput
}

/**
 * UsuarioCountOutputType without action
 */
export type UsuarioCountOutputTypeCountPastor_solicitudesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SolicitudWhereInput
}


export type UsuarioSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  email?: boolean
  password?: boolean
  rut?: boolean
  direccion?: boolean
  telefono?: boolean
  telefono_emergencia?: boolean
  fecha_nacimiento?: boolean
  foto_url?: boolean
  iglesia_id?: boolean
  rol_id?: boolean
  created_at?: boolean
  iglesia?: boolean | Prisma.IglesiaDefaultArgs<ExtArgs>
  rol?: boolean | Prisma.RolDefaultArgs<ExtArgs>
  inscripciones?: boolean | Prisma.Usuario$inscripcionesArgs<ExtArgs>
  solicitudes?: boolean | Prisma.Usuario$solicitudesArgs<ExtArgs>
  pastor_solicitudes?: boolean | Prisma.Usuario$pastor_solicitudesArgs<ExtArgs>
  _count?: boolean | Prisma.UsuarioCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["usuario"]>

export type UsuarioSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  email?: boolean
  password?: boolean
  rut?: boolean
  direccion?: boolean
  telefono?: boolean
  telefono_emergencia?: boolean
  fecha_nacimiento?: boolean
  foto_url?: boolean
  iglesia_id?: boolean
  rol_id?: boolean
  created_at?: boolean
  iglesia?: boolean | Prisma.IglesiaDefaultArgs<ExtArgs>
  rol?: boolean | Prisma.RolDefaultArgs<ExtArgs>
}, ExtArgs["result"]["usuario"]>

export type UsuarioSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  email?: boolean
  password?: boolean
  rut?: boolean
  direccion?: boolean
  telefono?: boolean
  telefono_emergencia?: boolean
  fecha_nacimiento?: boolean
  foto_url?: boolean
  iglesia_id?: boolean
  rol_id?: boolean
  created_at?: boolean
  iglesia?: boolean | Prisma.IglesiaDefaultArgs<ExtArgs>
  rol?: boolean | Prisma.RolDefaultArgs<ExtArgs>
}, ExtArgs["result"]["usuario"]>

export type UsuarioSelectScalar = {
  id?: boolean
  nombre?: boolean
  email?: boolean
  password?: boolean
  rut?: boolean
  direccion?: boolean
  telefono?: boolean
  telefono_emergencia?: boolean
  fecha_nacimiento?: boolean
  foto_url?: boolean
  iglesia_id?: boolean
  rol_id?: boolean
  created_at?: boolean
}

export type UsuarioOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nombre" | "email" | "password" | "rut" | "direccion" | "telefono" | "telefono_emergencia" | "fecha_nacimiento" | "foto_url" | "iglesia_id" | "rol_id" | "created_at", ExtArgs["result"]["usuario"]>
export type UsuarioInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  iglesia?: boolean | Prisma.IglesiaDefaultArgs<ExtArgs>
  rol?: boolean | Prisma.RolDefaultArgs<ExtArgs>
  inscripciones?: boolean | Prisma.Usuario$inscripcionesArgs<ExtArgs>
  solicitudes?: boolean | Prisma.Usuario$solicitudesArgs<ExtArgs>
  pastor_solicitudes?: boolean | Prisma.Usuario$pastor_solicitudesArgs<ExtArgs>
  _count?: boolean | Prisma.UsuarioCountOutputTypeDefaultArgs<ExtArgs>
}
export type UsuarioIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  iglesia?: boolean | Prisma.IglesiaDefaultArgs<ExtArgs>
  rol?: boolean | Prisma.RolDefaultArgs<ExtArgs>
}
export type UsuarioIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  iglesia?: boolean | Prisma.IglesiaDefaultArgs<ExtArgs>
  rol?: boolean | Prisma.RolDefaultArgs<ExtArgs>
}

export type $UsuarioPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Usuario"
  objects: {
    iglesia: Prisma.$IglesiaPayload<ExtArgs>
    rol: Prisma.$RolPayload<ExtArgs>
    inscripciones: Prisma.$InscripcionPayload<ExtArgs>[]
    solicitudes: Prisma.$SolicitudPayload<ExtArgs>[]
    pastor_solicitudes: Prisma.$SolicitudPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nombre: string
    email: string
    password: string
    rut: string
    direccion: string
    telefono: string
    telefono_emergencia: string
    fecha_nacimiento: Date
    foto_url: string
    iglesia_id: string
    rol_id: string
    created_at: Date
  }, ExtArgs["result"]["usuario"]>
  composites: {}
}

export type UsuarioGetPayload<S extends boolean | null | undefined | UsuarioDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UsuarioPayload, S>

export type UsuarioCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UsuarioFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UsuarioCountAggregateInputType | true
  }

export interface UsuarioDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Usuario'], meta: { name: 'Usuario' } }
  /**
   * Find zero or one Usuario that matches the filter.
   * @param {UsuarioFindUniqueArgs} args - Arguments to find a Usuario
   * @example
   * // Get one Usuario
   * const usuario = await prisma.usuario.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UsuarioFindUniqueArgs>(args: Prisma.SelectSubset<T, UsuarioFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Usuario that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UsuarioFindUniqueOrThrowArgs} args - Arguments to find a Usuario
   * @example
   * // Get one Usuario
   * const usuario = await prisma.usuario.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UsuarioFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UsuarioFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Usuario that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuarioFindFirstArgs} args - Arguments to find a Usuario
   * @example
   * // Get one Usuario
   * const usuario = await prisma.usuario.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UsuarioFindFirstArgs>(args?: Prisma.SelectSubset<T, UsuarioFindFirstArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Usuario that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuarioFindFirstOrThrowArgs} args - Arguments to find a Usuario
   * @example
   * // Get one Usuario
   * const usuario = await prisma.usuario.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UsuarioFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UsuarioFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Usuarios that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuarioFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Usuarios
   * const usuarios = await prisma.usuario.findMany()
   * 
   * // Get first 10 Usuarios
   * const usuarios = await prisma.usuario.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const usuarioWithIdOnly = await prisma.usuario.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UsuarioFindManyArgs>(args?: Prisma.SelectSubset<T, UsuarioFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Usuario.
   * @param {UsuarioCreateArgs} args - Arguments to create a Usuario.
   * @example
   * // Create one Usuario
   * const Usuario = await prisma.usuario.create({
   *   data: {
   *     // ... data to create a Usuario
   *   }
   * })
   * 
   */
  create<T extends UsuarioCreateArgs>(args: Prisma.SelectSubset<T, UsuarioCreateArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Usuarios.
   * @param {UsuarioCreateManyArgs} args - Arguments to create many Usuarios.
   * @example
   * // Create many Usuarios
   * const usuario = await prisma.usuario.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UsuarioCreateManyArgs>(args?: Prisma.SelectSubset<T, UsuarioCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Usuarios and returns the data saved in the database.
   * @param {UsuarioCreateManyAndReturnArgs} args - Arguments to create many Usuarios.
   * @example
   * // Create many Usuarios
   * const usuario = await prisma.usuario.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Usuarios and only return the `id`
   * const usuarioWithIdOnly = await prisma.usuario.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UsuarioCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UsuarioCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Usuario.
   * @param {UsuarioDeleteArgs} args - Arguments to delete one Usuario.
   * @example
   * // Delete one Usuario
   * const Usuario = await prisma.usuario.delete({
   *   where: {
   *     // ... filter to delete one Usuario
   *   }
   * })
   * 
   */
  delete<T extends UsuarioDeleteArgs>(args: Prisma.SelectSubset<T, UsuarioDeleteArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Usuario.
   * @param {UsuarioUpdateArgs} args - Arguments to update one Usuario.
   * @example
   * // Update one Usuario
   * const usuario = await prisma.usuario.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UsuarioUpdateArgs>(args: Prisma.SelectSubset<T, UsuarioUpdateArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Usuarios.
   * @param {UsuarioDeleteManyArgs} args - Arguments to filter Usuarios to delete.
   * @example
   * // Delete a few Usuarios
   * const { count } = await prisma.usuario.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UsuarioDeleteManyArgs>(args?: Prisma.SelectSubset<T, UsuarioDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Usuarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuarioUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Usuarios
   * const usuario = await prisma.usuario.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UsuarioUpdateManyArgs>(args: Prisma.SelectSubset<T, UsuarioUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Usuarios and returns the data updated in the database.
   * @param {UsuarioUpdateManyAndReturnArgs} args - Arguments to update many Usuarios.
   * @example
   * // Update many Usuarios
   * const usuario = await prisma.usuario.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Usuarios and only return the `id`
   * const usuarioWithIdOnly = await prisma.usuario.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UsuarioUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UsuarioUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Usuario.
   * @param {UsuarioUpsertArgs} args - Arguments to update or create a Usuario.
   * @example
   * // Update or create a Usuario
   * const usuario = await prisma.usuario.upsert({
   *   create: {
   *     // ... data to create a Usuario
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Usuario we want to update
   *   }
   * })
   */
  upsert<T extends UsuarioUpsertArgs>(args: Prisma.SelectSubset<T, UsuarioUpsertArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Usuarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuarioCountArgs} args - Arguments to filter Usuarios to count.
   * @example
   * // Count the number of Usuarios
   * const count = await prisma.usuario.count({
   *   where: {
   *     // ... the filter for the Usuarios we want to count
   *   }
   * })
  **/
  count<T extends UsuarioCountArgs>(
    args?: Prisma.Subset<T, UsuarioCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UsuarioCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Usuario.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuarioAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UsuarioAggregateArgs>(args: Prisma.Subset<T, UsuarioAggregateArgs>): Prisma.PrismaPromise<GetUsuarioAggregateType<T>>

  /**
   * Group by Usuario.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuarioGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UsuarioGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UsuarioGroupByArgs['orderBy'] }
      : { orderBy?: UsuarioGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UsuarioGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUsuarioGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Usuario model
 */
readonly fields: UsuarioFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Usuario.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UsuarioClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  iglesia<T extends Prisma.IglesiaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.IglesiaDefaultArgs<ExtArgs>>): Prisma.Prisma__IglesiaClient<runtime.Types.Result.GetResult<Prisma.$IglesiaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  rol<T extends Prisma.RolDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RolDefaultArgs<ExtArgs>>): Prisma.Prisma__RolClient<runtime.Types.Result.GetResult<Prisma.$RolPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  inscripciones<T extends Prisma.Usuario$inscripcionesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Usuario$inscripcionesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  solicitudes<T extends Prisma.Usuario$solicitudesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Usuario$solicitudesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  pastor_solicitudes<T extends Prisma.Usuario$pastor_solicitudesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Usuario$pastor_solicitudesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SolicitudPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Usuario model
 */
export interface UsuarioFieldRefs {
  readonly id: Prisma.FieldRef<"Usuario", 'String'>
  readonly nombre: Prisma.FieldRef<"Usuario", 'String'>
  readonly email: Prisma.FieldRef<"Usuario", 'String'>
  readonly password: Prisma.FieldRef<"Usuario", 'String'>
  readonly rut: Prisma.FieldRef<"Usuario", 'String'>
  readonly direccion: Prisma.FieldRef<"Usuario", 'String'>
  readonly telefono: Prisma.FieldRef<"Usuario", 'String'>
  readonly telefono_emergencia: Prisma.FieldRef<"Usuario", 'String'>
  readonly fecha_nacimiento: Prisma.FieldRef<"Usuario", 'DateTime'>
  readonly foto_url: Prisma.FieldRef<"Usuario", 'String'>
  readonly iglesia_id: Prisma.FieldRef<"Usuario", 'String'>
  readonly rol_id: Prisma.FieldRef<"Usuario", 'String'>
  readonly created_at: Prisma.FieldRef<"Usuario", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Usuario findUnique
 */
export type UsuarioFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  /**
   * Filter, which Usuario to fetch.
   */
  where: Prisma.UsuarioWhereUniqueInput
}

/**
 * Usuario findUniqueOrThrow
 */
export type UsuarioFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  /**
   * Filter, which Usuario to fetch.
   */
  where: Prisma.UsuarioWhereUniqueInput
}

/**
 * Usuario findFirst
 */
export type UsuarioFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  /**
   * Filter, which Usuario to fetch.
   */
  where?: Prisma.UsuarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usuarios to fetch.
   */
  orderBy?: Prisma.UsuarioOrderByWithRelationInput | Prisma.UsuarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Usuarios.
   */
  cursor?: Prisma.UsuarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usuarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usuarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Usuarios.
   */
  distinct?: Prisma.UsuarioScalarFieldEnum | Prisma.UsuarioScalarFieldEnum[]
}

/**
 * Usuario findFirstOrThrow
 */
export type UsuarioFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  /**
   * Filter, which Usuario to fetch.
   */
  where?: Prisma.UsuarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usuarios to fetch.
   */
  orderBy?: Prisma.UsuarioOrderByWithRelationInput | Prisma.UsuarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Usuarios.
   */
  cursor?: Prisma.UsuarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usuarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usuarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Usuarios.
   */
  distinct?: Prisma.UsuarioScalarFieldEnum | Prisma.UsuarioScalarFieldEnum[]
}

/**
 * Usuario findMany
 */
export type UsuarioFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  /**
   * Filter, which Usuarios to fetch.
   */
  where?: Prisma.UsuarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usuarios to fetch.
   */
  orderBy?: Prisma.UsuarioOrderByWithRelationInput | Prisma.UsuarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Usuarios.
   */
  cursor?: Prisma.UsuarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usuarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usuarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Usuarios.
   */
  distinct?: Prisma.UsuarioScalarFieldEnum | Prisma.UsuarioScalarFieldEnum[]
}

/**
 * Usuario create
 */
export type UsuarioCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  /**
   * The data needed to create a Usuario.
   */
  data: Prisma.XOR<Prisma.UsuarioCreateInput, Prisma.UsuarioUncheckedCreateInput>
}

/**
 * Usuario createMany
 */
export type UsuarioCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Usuarios.
   */
  data: Prisma.UsuarioCreateManyInput | Prisma.UsuarioCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Usuario createManyAndReturn
 */
export type UsuarioCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * The data used to create many Usuarios.
   */
  data: Prisma.UsuarioCreateManyInput | Prisma.UsuarioCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Usuario update
 */
export type UsuarioUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  /**
   * The data needed to update a Usuario.
   */
  data: Prisma.XOR<Prisma.UsuarioUpdateInput, Prisma.UsuarioUncheckedUpdateInput>
  /**
   * Choose, which Usuario to update.
   */
  where: Prisma.UsuarioWhereUniqueInput
}

/**
 * Usuario updateMany
 */
export type UsuarioUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Usuarios.
   */
  data: Prisma.XOR<Prisma.UsuarioUpdateManyMutationInput, Prisma.UsuarioUncheckedUpdateManyInput>
  /**
   * Filter which Usuarios to update
   */
  where?: Prisma.UsuarioWhereInput
  /**
   * Limit how many Usuarios to update.
   */
  limit?: number
}

/**
 * Usuario updateManyAndReturn
 */
export type UsuarioUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * The data used to update Usuarios.
   */
  data: Prisma.XOR<Prisma.UsuarioUpdateManyMutationInput, Prisma.UsuarioUncheckedUpdateManyInput>
  /**
   * Filter which Usuarios to update
   */
  where?: Prisma.UsuarioWhereInput
  /**
   * Limit how many Usuarios to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Usuario upsert
 */
export type UsuarioUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  /**
   * The filter to search for the Usuario to update in case it exists.
   */
  where: Prisma.UsuarioWhereUniqueInput
  /**
   * In case the Usuario found by the `where` argument doesn't exist, create a new Usuario with this data.
   */
  create: Prisma.XOR<Prisma.UsuarioCreateInput, Prisma.UsuarioUncheckedCreateInput>
  /**
   * In case the Usuario was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UsuarioUpdateInput, Prisma.UsuarioUncheckedUpdateInput>
}

/**
 * Usuario delete
 */
export type UsuarioDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  /**
   * Filter which Usuario to delete.
   */
  where: Prisma.UsuarioWhereUniqueInput
}

/**
 * Usuario deleteMany
 */
export type UsuarioDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Usuarios to delete
   */
  where?: Prisma.UsuarioWhereInput
  /**
   * Limit how many Usuarios to delete.
   */
  limit?: number
}

/**
 * Usuario.inscripciones
 */
export type Usuario$inscripcionesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  where?: Prisma.InscripcionWhereInput
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  cursor?: Prisma.InscripcionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InscripcionScalarFieldEnum | Prisma.InscripcionScalarFieldEnum[]
}

/**
 * Usuario.solicitudes
 */
export type Usuario$solicitudesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  where?: Prisma.SolicitudWhereInput
  orderBy?: Prisma.SolicitudOrderByWithRelationInput | Prisma.SolicitudOrderByWithRelationInput[]
  cursor?: Prisma.SolicitudWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SolicitudScalarFieldEnum | Prisma.SolicitudScalarFieldEnum[]
}

/**
 * Usuario.pastor_solicitudes
 */
export type Usuario$pastor_solicitudesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Solicitud
   */
  select?: Prisma.SolicitudSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Solicitud
   */
  omit?: Prisma.SolicitudOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SolicitudInclude<ExtArgs> | null
  where?: Prisma.SolicitudWhereInput
  orderBy?: Prisma.SolicitudOrderByWithRelationInput | Prisma.SolicitudOrderByWithRelationInput[]
  cursor?: Prisma.SolicitudWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SolicitudScalarFieldEnum | Prisma.SolicitudScalarFieldEnum[]
}

/**
 * Usuario without action
 */
export type UsuarioDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
}
